Repository tektoncd/hub, pull requests merged in 2020-09, with the labels that each got.

#75 Renames `type` to `kind` for resources to match the kubernetes kind
  api/design/resource.go
  api/design/type.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/resource/client/cli.go
  api/gen/http/resource/client/client.go
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/client/paths.go
  api/gen/http/resource/client/types.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/paths.go
  api/gen/http/resource/server/server.go
  api/gen/http/resource/server/types.go
  api/gen/resource/client.go
  api/gen/resource/endpoints.go
  api/gen/resource/service.go
  api/gen/resource/views/view.go
  api/pkg/db/migration/202008121043_add_not_null_constraint_to_resource_and_resource_version.go
  api/pkg/db/model/model.go
  api/pkg/db/validation/validation_test.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestByID_Http.golden
  api/pkg/service/resource/testdata/TestByKindNameVersion_Http.golden
  api/pkg/service/resource/testdata/TestByKindName_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_Http.golden
  api/pkg/service/resource/testdata/TestList_Http_NoLimit.golden
  api/pkg/service/resource/testdata/TestList_Http_WithLimit.golden
  api/pkg/service/resource/testdata/TestQuery_Http.golden
  api/test/fixtures/resources.yaml
Labels: approved, lgtm, size/XXL

#73 Adds a cronjob which allows catalog to be refreshed
  api/config/32-catalog-refresh-cronjob.yaml
  api/config/init/31-catalog-refresh-secret.yaml
Labels: approved, lgtm, size/M

#81 Modifies query api for resources
  api/design/resource.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
  api/gen/http/resource/client/cli.go
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/types.go
  api/gen/resource/service.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestQueryWithAllParams_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithExactName_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKindsAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithTags_Http.golden
Labels: approved, lgtm, size/XXL

#80 Adds goa plugin for zap Suggared Logger
  api/cmd/api/http.go
  api/cmd/api/main.go
  api/cmd/db/main.go
  api/design/api.go
  api/gen/log/logger.go
  api/pkg/app/app.go
  api/pkg/app/service.go
  api/pkg/db/initializer/initiailizer.go
  api/pkg/db/migration/202006071000_add_resource_and_resource_versions_tables.go
  api/pkg/db/migration/202006091100_add_minimum_pipeline_version_column_in_resource_version.go
  api/pkg/db/migration/202008071700_add_org_and_drop_owner_column_in_catalog.go
  api/pkg/db/migration/202008121043_add_not_null_constraint_to_resource_and_resource_version.go
  api/pkg/db/migration/migration.go
  api/pkg/service/auth/auth.go
  api/pkg/service/auth/service.go
  api/pkg/service/category/category.go
  api/pkg/service/rating/rating.go
  api/pkg/service/rating/rating_http_test.go
  api/pkg/service/resource/resource.go
  api/pkg/testutils/db.go
Labels: approved, lgtm, size/XL

#85 Adds missing tests for the resources api
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestByKindNameVersion_Http.golden
  api/pkg/service/resource/testdata/TestList_Http_NoLimit.golden
  api/test/fixtures/resource_tags.yaml
  api/test/fixtures/resource_versions.yaml
  api/test/fixtures/resources.yaml
Labels: approved, lgtm, size/M

#76 Updates Developement doc for authentication setup
  docs/DEVELOPMENT.md
Labels: approved, lgtm, size/L

#91 Cleanup: removes db migrations
  api/pkg/db/migration/202006071000_add_resource_and_resource_versions_tables.go
  api/pkg/db/migration/202008071700_add_org_and_drop_owner_column_in_catalog.go
  api/pkg/db/migration/202008121043_add_not_null_constraint_to_resource_and_resource_version.go
  api/pkg/db/migration/migration.go
  api/pkg/db/migration/migration_template.go
Labels: approved, lgtm, size/L

#94 Adds JWT Security for Catalog refresh API and tests (Staging)
  api/design/catalog.go
  api/design/type.go
  api/gen/admin/endpoints.go
  api/gen/catalog/endpoints.go
  api/gen/catalog/service.go
  api/gen/http/admin/client/cli.go
  api/gen/http/catalog/client/cli.go
  api/gen/http/catalog/client/encode_decode.go
  api/gen/http/catalog/client/types.go
  api/gen/http/catalog/server/encode_decode.go
  api/gen/http/catalog/server/types.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
  api/gen/http/resource/client/cli.go
  api/gen/rating/endpoints.go
  api/pkg/db/migration/migration.go
  api/pkg/service/catalog/catalog.go
  api/pkg/service/catalog/catalog_http_test.go
  api/pkg/service/catalog/catalog_test.go
  api/test/fixtures/scopes.yaml
Labels: approved, lgtm, size/XXL

#95 Fix: Changes Errors in API to lowercase
  api/cmd/api/main.go
  api/pkg/service/category/category.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_test.go
Labels: approved, lgtm, size/S

#96 Moves reading of config file data to FromEnvFile
  api/pkg/app/app.go
Labels: approved, lgtm, size/M

#87 Modifies status api to add db transaction
  api/cmd/api/main.go
  api/design/status.go
  api/design/type.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
  api/gen/http/resource/client/cli.go
  api/gen/http/status/client/encode_decode.go
  api/gen/http/status/client/types.go
  api/gen/http/status/server/encode_decode.go
  api/gen/http/status/server/types.go
  api/gen/status/service.go
  api/pkg/app/app.go
  api/pkg/service/status/status.go
  api/pkg/service/status/status_http_test.go
  api/pkg/service/status/testdata/TestDB_NotOK.golden
  api/pkg/service/status/testdata/TestOk_http.golden
Labels: approved, lgtm, size/XXL

#98 Docs: Improves authentication steps in Development.md
  docs/DEVELOPMENT.md
Labels: approved, lgtm, size/S
