Repository tektoncd/hub, pull requests merged in 2020-11, with the labels that each got.

#70 UI: Adds store for resources using mobx-state-tree
  ui/package-lock.json
  ui/package.json
  ui/src/api/index.ts
  ui/src/api/testutil.ts
  ui/src/components/App/App.test.tsx
  ui/src/components/App/App.tsx
  ui/src/components/App/__snapshots__/App.test.tsx.snap
  ui/src/components/App/index.tsx
  ui/src/components/CategoryFilter/CategoryFilter.test.tsx
  ui/src/components/CategoryFilter/CategoryFilter.tsx
  ui/src/components/CategoryFilter/__snapshots__/CategoryFilter.test.tsx.snap
  ui/src/components/Filter/Filter.tsx
  ui/src/index.tsx
  ui/src/store/__snapshots__/catalog.test.ts.snap
  ui/src/store/__snapshots__/category.test.ts.snap
  ui/src/store/__snapshots__/kind.test.ts.snap
  ui/src/store/__snapshots__/resource.test.ts.snap
  ui/src/store/catalog.test.ts
  ui/src/store/catalog.ts
  ui/src/store/category.test.ts
  ui/src/store/category.ts
  ui/src/store/kind.test.ts
  ui/src/store/kind.ts
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
  ui/src/store/root.tsx
  ui/src/store/testdata/resources.json
  ui/src/store/utils.test.ts
  ui/src/store/utils.ts
Labels: approved, lgtm, size/XXL

#131 Upgrades gorm to 2.0
  api/cmd/api/main.go
  api/cmd/db/main.go
  api/go.mod
  api/go.sum
  api/pkg/app/app.go
  api/pkg/app/gorm_logger.go
  api/pkg/app/service.go
  api/pkg/db/initializer/initializer.go
  api/pkg/db/migration/202010061403_rename_name_to_agent_name_in_user.go
  api/pkg/db/migration/202010071100_create_config_table.go
  api/pkg/db/migration/migration.go
  api/pkg/db/migration/migration_template.go
  api/pkg/db/model/model.go
  api/pkg/db/model/sync_job.go
  api/pkg/db/validation/validation_test.go
  api/pkg/parser/parser.go
  api/pkg/service/admin/admin.go
  api/pkg/service/admin/admin_http_test.go
  api/pkg/service/auth/auth.go
  api/pkg/service/auth/auth_http_test.go
  api/pkg/service/auth/service.go
  api/pkg/service/catalog/catalog.go
  api/pkg/service/catalog/catalog_http_test.go
  api/pkg/service/catalog/catalog_test.go
  api/pkg/service/catalog/syncer.go
  api/pkg/service/category/category.go
  api/pkg/service/category/category_http_test.go
  api/pkg/service/category/category_test.go
  api/pkg/service/rating/rating.go
  api/pkg/service/rating/rating_http_test.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestList_Http_NoLimit.golden
  api/pkg/service/status/status.go
  api/pkg/service/status/status_http_test.go
  api/pkg/testutils/db.go
  api/test/fixtures/resource_versions.yaml
Labels: approved, lgtm, size/XL

#135 Adds left pane for the dashboard
  ui/src/components/App/__snapshots__/App.test.tsx.snap
  ui/src/components/Filter/Filter.css
  ui/src/components/Filter/Filter.test.tsx
  ui/src/components/Filter/index.tsx
  ui/src/components/LeftPane/LeftPane.css
  ui/src/components/LeftPane/LeftPane.test.tsx
  ui/src/components/LeftPane/__snapshots__/LeftPane.test.tsx.snap
  ui/src/components/LeftPane/index.tsx
  ui/src/containers/App/App.test.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/App/index.tsx
  ui/src/containers/CatalogFilter/CatalogFilter.test.tsx
  ui/src/containers/CatalogFilter/__snapshots__/CatalogFilter.test.tsx.snap
  ui/src/containers/CatalogFilter/index.tsx
  ui/src/containers/CategoryFilter/CategoryFilter.test.tsx
  ui/src/containers/CategoryFilter/__snapshots__/CategoryFilter.test.tsx.snap
  ui/src/containers/CategoryFilter/index.tsx
  ui/src/containers/KindFilter/KindFilter.test.tsx
  ui/src/containers/KindFilter/__snapshots__/KindFilter.test.tsx.snap
  ui/src/containers/KindFilter/index.tsx
  ui/src/containers/SortDropDown/SortDropDown.css
  ui/src/containers/SortDropDown/SortDropDown.test.tsx
  ui/src/containers/SortDropDown/__snapshots__/SortDropDown.test.tsx.snap
  ui/src/containers/SortDropDown/index.tsx
  ui/src/index.tsx
  ui/src/store/resource.ts
Labels: approved, lgtm, size/XL

#122 Add Icons for Filter Components
  ui/src/common/icons.ts
  ui/src/common/titlecase.test.ts
  ui/src/common/titlecase.ts
  ui/src/components/Filter/index.tsx
  ui/src/components/Icon/Icon.css
  ui/src/components/Icon/Icon.test.tsx
  ui/src/components/Icon/__snapshots__/Icon.test.tsx.snap
  ui/src/components/Icon/index.tsx
  ui/src/containers/CatalogFilter/__snapshots__/CatalogFilter.test.tsx.snap
  ui/src/containers/CategoryFilter/__snapshots__/CategoryFilter.test.tsx.snap
  ui/src/containers/KindFilter/KindFilter.test.tsx
  ui/src/containers/KindFilter/__snapshots__/KindFilter.test.tsx.snap
  ui/src/store/catalog.test.ts
  ui/src/store/catalog.ts
  ui/src/store/kind.test.ts
  ui/src/store/kind.ts
Labels: approved, lgtm, size/L
