Repository tektoncd/hub, pull requests merged in 2020-07, with the labels that each got.

#27 Database Migration to create tables for resources
  api/cmd/db/main.go
  api/cmd/db/migration.go
  api/pkg/db/model/model.go
Labels: approved, lgtm, size/L

#30 Run postgres service instead of using DIND to run database
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#32 Adds minPipelinesVersion field in ResourceVersion Table
  api/cmd/db/migration.go
  api/pkg/db/model/model.go
Labels: approved, lgtm, size/S

#29 Updates Development.md and adds deployment files
  DEVELOPMENT.md
  api/cmd/api-cli/http.go
  api/cmd/api-cli/main.go
  api/cmd/api/http.go
  api/cmd/api/main.go
  api/config/00-namespace.yaml
  api/config/10-db-secret.yaml
  api/config/11-db-pvc.yaml
  api/config/12-db-deployment.yaml
  api/config/13-db-service.yaml
  api/config/20-api-deployment.yaml
  api/config/db-migration/14-db-migration.yaml
  api/config/gke/21-api-service.yaml
  api/config/openshift/21-api-service.yaml
  api/config/openshift/22-api-route.yaml
  docs/DEVELOPMENT.md
Labels: approved, lgtm, size/L

#35 Updates endpoint test to use golden file and run tests serially
  api/go.mod
  api/go.sum
  api/pkg/app/app.go
  api/pkg/service/category/category.go
  api/pkg/service/category/category_http_test.go
  api/pkg/service/category/category_test.go
  api/pkg/service/category/testdata/TestCategories_List_Http.golden
  api/pkg/testutils/config.go
  api/pkg/testutils/db.go
  api/pkg/testutils/run.go
  api/pkg/testutils/utils.go
  api/test/fixtures/categories.yaml
  api/test/fixtures/tags.yaml
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L

#49 Adds `/` api to check if the server has started successfully
  api/cmd/api/http.go
  api/cmd/api/main.go
  api/config/20-api-deployment.yaml
  api/design/api.go
  api/design/status.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/status/client/cli.go
  api/gen/http/status/client/client.go
  api/gen/http/status/client/encode_decode.go
  api/gen/http/status/client/paths.go
  api/gen/http/status/client/types.go
  api/gen/http/status/server/encode_decode.go
  api/gen/http/status/server/paths.go
  api/gen/http/status/server/server.go
  api/gen/http/status/server/types.go
  api/gen/status/client.go
  api/gen/status/endpoints.go
  api/gen/status/service.go
  api/go.sum
  api/pkg/service/status/status.go
  api/pkg/service/status/status_http_test.go
Labels: approved, lgtm, size/XL

#50 Update README.md to add preview link
  README.md
Labels: approved, lgtm, size/M

#55 Cleanup: make db image env variabes names uniform across project
  api/.env.dev
  api/config/10-db-secret.yaml
  api/config/12-db-deployment.yaml
  api/config/20-api-deployment.yaml
  api/config/db-migration/14-db-migration.yaml
  api/pkg/app/app.go
  api/test/config/env.test
  docs/DEVELOPMENT.md
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M

#47 Adds Config file to populate application data in DB
  api/.env.dev
  api/cmd/api/main.go
  api/cmd/db/migration.go
  api/config/20-api-configmap.yaml
  api/config/21-api-deployment.yaml
  api/config/db-migration/14-db-migration.yaml
  api/design/status.go
  api/go.mod
  api/go.sum
  api/pkg/app/app.go
  api/pkg/app/data.go
  api/pkg/db/initializer/initiailizer.go
  api/pkg/db/model/model.go
  api/pkg/service/status/status.go
  api/pkg/service/status/status_http_test.go
  api/test/config/config.yaml
  api/test/config/env.test
  config.yaml
Labels: approved, lgtm, size/XL
