Repository tektoncd/hub, pull requests merged in 2020-10, with the labels that each got.

#102 Adds users for 'catalog:refresh' scope in config file
  config.yaml
Labels: approved, lgtm, size/XS

#103 Changes default api server mode to production
  api/pkg/app/app.go
  api/pkg/service/catalog/syncer.go
Labels: approved, lgtm, size/S

#104 Renames column name `Name` to `AgentName` in users table
  api/pkg/db/migration/202010061403_rename_name_to_agent_name_in_user.go
  api/pkg/db/migration/migration.go
  api/pkg/db/model/model.go
  api/pkg/service/admin/admin.go
  api/test/fixtures/users.yaml
Labels: approved, lgtm, size/M

#107 Api probe delay
  api/config/12-db-deployment.yaml
  api/config/31-api-deployment.yaml
Labels: approved, lgtm, size/XS

#111 Cleanup: removes addScopes from migration
  api/pkg/db/migration/migration.go
Labels: approved, lgtm, size/S

#113 Removes user validation in API methods
  api/pkg/service/catalog/catalog.go
  api/pkg/service/rating/rating.go
Labels: approved, lgtm, size/M

#112 Replaces hardcoded jwt with function to create it with required scopes
  api/pkg/service/admin/admin_http_test.go
  api/pkg/service/admin/admin_test.go
  api/pkg/service/auth/auth_http_test.go
  api/pkg/service/auth/auth_test.go
  api/pkg/service/catalog/catalog_http_test.go
  api/pkg/service/catalog/catalog_test.go
  api/pkg/service/rating/rating_http_test.go
  api/pkg/service/rating/rating_test.go
  api/pkg/testutils/utils.go
  api/test/fixtures/scopes.yaml
  api/test/fixtures/user_resource_ratings.yaml
  api/test/fixtures/user_scopes.yaml
  api/test/fixtures/users.yaml
Labels: approved, lgtm, size/L

#116 Updates CatalogKindName API to return a resource instead of array
  api/design/resource.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/client/types.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/types.go
  api/gen/resource/client.go
  api/gen/resource/endpoints.go
  api/gen/resource/service.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestByCatalogKindName_Http.golden
Labels: approved, lgtm, size/XL

#114 Move tkn-hub into api for easier vendoring into tkn
  api/cmd/tkn-hub/main.go
  api/go.mod
  api/go.sum
  api/pkg/cli/app/app.go
  api/pkg/cli/cmd/root.go
  api/pkg/cli/cmd/search/search.go
  api/pkg/cli/cmd/search/search_test.go
  api/pkg/cli/cmd/search/testdata/TestSearch_JSONFormat.golden
  api/pkg/cli/cmd/search/testdata/TestSearch_TableFormat.golden
  api/pkg/cli/flag/kind.go
  api/pkg/cli/flag/kind_test.go
  api/pkg/cli/flag/validate.go
  api/pkg/cli/flag/validate_test.go
  api/pkg/cli/formatter/field.go
  api/pkg/cli/formatter/field_test.go
  api/pkg/cli/formatter/json.go
  api/pkg/cli/formatter/json_test.go
  api/pkg/cli/hub/hub.go
  api/pkg/cli/hub/hub_test.go
  api/pkg/cli/hub/search.go
  api/pkg/cli/hub/search_test.go
  api/pkg/cli/printer/print.go
  api/pkg/cli/test/config.go
  cli/go.mod
  cli/go.sum
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XL

#118 CLI: Validates kinds for search command using hub parser
  api/pkg/cli/cmd/search/search.go
  api/pkg/cli/cmd/search/search_test.go
  api/pkg/cli/flag/kind.go
  api/pkg/cli/flag/kind_test.go
  api/pkg/cli/flag/validate.go
  api/pkg/cli/flag/validate_test.go
Labels: approved, lgtm, size/L

#119 CLI: Replaces 'catalog' with 'from' in get cmd & adds examples
  api/pkg/cli/cmd/get/get.go
  api/pkg/cli/cmd/get/get_test.go
  api/pkg/cli/cmd/search/search.go
Labels: approved, lgtm, size/M

#125 CLI: Updates examples to have Tekton Resource in Title case
  api/pkg/cli/cmd/get/get.go
  api/pkg/cli/cmd/get/get_test.go
Labels: approved, lgtm, size/S

#126 Updates Resource's updatedAt field to point ModifiedAt field in db
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/testdata/TestByCatalogKindNameVersion_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_Http.golden
  api/pkg/service/resource/testdata/TestByID_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_Http.golden
  api/pkg/service/resource/testdata/TestList_Http.golden
  api/pkg/service/resource/testdata/TestList_Http_NoLimit.golden
  api/pkg/service/resource/testdata/TestList_Http_WithLimit.golden
  api/pkg/service/resource/testdata/TestQueryWithAllParams_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithExactName_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKindsAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithTags_Http.golden
  api/pkg/service/resource/testdata/TestQuery_Http.golden
  api/test/fixtures/resource_versions.yaml
Labels: approved, lgtm, size/L
