Repository tektoncd/hub, pull requests merged in 2020-12, with the labels that each got.

#138 Fixes Date Time format to RFC3339 in APIs response
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/testdata/TestByCatalogKindNameVersion_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_Http.golden
  api/pkg/service/resource/testdata/TestByID_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_Http.golden
  api/pkg/service/resource/testdata/TestList_Http_NoLimit.golden
  api/pkg/service/resource/testdata/TestList_Http_WithLimit.golden
  api/pkg/service/resource/testdata/TestQueryWithAllParams_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithExactName_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKindsAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithTags_Http.golden
  api/pkg/service/resource/testdata/TestQuery_Http.golden
Labels: approved, lgtm, size/M

#134 CLI: Adds info command
  api/go.mod
  api/go.sum
  api/pkg/cli/cmd/info/info.go
  api/pkg/cli/cmd/info/info_test.go
  api/pkg/cli/cmd/info/testdata/TestInfoPipeline_Description.golden
  api/pkg/cli/cmd/info/testdata/TestInfoPipeline_WithVersion.golden
  api/pkg/cli/cmd/info/testdata/TestInfoTask_WithoutVersion.golden
  api/pkg/cli/cmd/info/testdata/TestPipelineTask_MultiLineDescription.golden
  api/pkg/cli/cmd/root.go
  api/pkg/cli/cmd/search/search.go
  api/pkg/cli/formatter/field.go
  api/pkg/cli/formatter/field_test.go
  api/pkg/cli/hub/get_resource.go
Labels: approved, lgtm, size/XL

#99 UI: Adds dashboard page layout
  ui/package-lock.json
  ui/package.json
  ui/public/index.html
  ui/src/assets/logo/background.jpg
  ui/src/assets/logo/logo.png
  ui/src/assets/logo/tekton.png
  ui/src/components/Background/Background.css
  ui/src/components/Background/Background.test.tsx
  ui/src/components/Background/__snapshots__/Background.test.tsx.snap
  ui/src/components/Background/index.tsx
  ui/src/components/Footer/Footer.css
  ui/src/components/Footer/Footer.test.tsx
  ui/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  ui/src/components/Footer/index.tsx
  ui/src/components/Header/Header.test.tsx
  ui/src/components/Header/__snapshots__/Header.test.tsx.snap
  ui/src/components/Header/index.tsx
  ui/src/containers/App/App.css
  ui/src/containers/App/App.test.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/App/index.tsx
  ui/src/containers/Details/Details.test.tsx
  ui/src/containers/Details/__snapshots__/Details.test.tsx.snap
  ui/src/containers/Details/index.tsx
  ui/src/containers/Resources/Resources.css
  ui/src/containers/Resources/Resources.test.tsx
  ui/src/containers/Resources/__snapshots__/Resources.test.tsx.snap
  ui/src/containers/Resources/index.tsx
  ui/src/containers/Search/Search.css
  ui/src/containers/Search/Search.test.tsx
  ui/src/containers/Search/__snapshots__/Search.test.tsx.snap
  ui/src/containers/Search/index.tsx
Labels: approved, lgtm, size/XXL

#121 CLI: Adds install command
  api/go.mod
  api/go.sum
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/cmd/install/install_test.go
  api/pkg/cli/cmd/install/testdata/foo-v0.3.yaml
  api/pkg/cli/cmd/root.go
  api/pkg/cli/hub/get_resource.go
  api/pkg/cli/installer/action.go
  api/pkg/cli/installer/action_test.go
  api/pkg/cli/installer/config.go
  api/pkg/cli/installer/gvr.go
  api/pkg/cli/installer/kube_action.go
  api/pkg/cli/kube/client.go
  api/pkg/cli/printer/print.go
  api/pkg/cli/test/builder/apiresource.go
  api/pkg/cli/test/builder/unstructured.go
  api/pkg/cli/test/client.go
  api/pkg/cli/test/helpers.go
Labels: approved, lgtm, size/XXL

#143 CLI: adds examples for info cmd
  api/pkg/cli/cmd/info/info.go
Labels: approved, lgtm, size/S

#145 CLI: Adds reinstall command
  api/pkg/cli/cmd/reinstall/reinstall.go
  api/pkg/cli/cmd/reinstall/reinstall_test.go
  api/pkg/cli/cmd/reinstall/testdata/foo-v0.3.yaml
  api/pkg/cli/cmd/root.go
  api/pkg/cli/installer/action.go
  api/pkg/cli/installer/config.go
  api/pkg/cli/installer/kube_action.go
Labels: approved, lgtm, size/XL

#142 CLI: Adds upgrade command
  api/go.mod
  api/go.sum
  api/pkg/cli/cmd/root.go
  api/pkg/cli/cmd/upgrade/testdata/foo-v0.3.yaml
  api/pkg/cli/cmd/upgrade/upgrade.go
  api/pkg/cli/cmd/upgrade/upgrade_test.go
  api/pkg/cli/installer/action.go
Labels: approved, lgtm, size/XL

#147 CLI: Improves error messages in install, reinstall & upgrade cmd
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/cmd/install/install_test.go
  api/pkg/cli/cmd/reinstall/reinstall.go
  api/pkg/cli/cmd/reinstall/reinstall_test.go
  api/pkg/cli/cmd/upgrade/upgrade.go
  api/pkg/cli/cmd/upgrade/upgrade_test.go
  api/pkg/cli/hub/get_resource.go
Labels: approved, lgtm, size/L

#148 Minor filter fix
  ui/src/components/Filter/Filter.css
  ui/src/components/Filter/index.tsx
  ui/src/containers/CatalogFilter/__snapshots__/CatalogFilter.test.tsx.snap
  ui/src/containers/CategoryFilter/__snapshots__/CategoryFilter.test.tsx.snap
  ui/src/containers/KindFilter/__snapshots__/KindFilter.test.tsx.snap
Labels: approved, lgtm, size/M

#144 UI: Adds search and sort implementation
  ui/src/components/Cards/__snapshots__/Cards.test.tsx.snap
  ui/src/components/Header/Header.test.tsx
  ui/src/components/Header/__snapshots__/Header.test.tsx.snap
  ui/src/components/LeftPane/__snapshots__/LeftPane.test.tsx.snap
  ui/src/components/LeftPane/index.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/Resources/__snapshots__/Resources.test.tsx.snap
  ui/src/containers/Search/Search.test.tsx
  ui/src/containers/Search/__snapshots__/Search.test.tsx.snap
  ui/src/containers/Search/index.tsx
  ui/src/containers/SortDropDown/SortDropDown.css
  ui/src/containers/SortDropDown/SortDropDown.test.tsx
  ui/src/containers/SortDropDown/__snapshots__/SortDropDown.test.tsx.snap
  ui/src/containers/SortDropDown/index.tsx
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
Labels: approved, lgtm, size/XL

#150 CLI: Improves command description and add examples
  api/pkg/cli/cmd/info/info.go
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/cmd/reinstall/reinstall.go
  api/pkg/cli/cmd/upgrade/upgrade.go
Labels: approved, lgtm, size/S

#151 UI:Adds github login
  ui/package-lock.json
  ui/package.json
  ui/public/config.js
  ui/src/api/index.ts
  ui/src/api/testutil.ts
  ui/src/assets/logo/imgAvatar.png
  ui/src/components/Header/Header.test.tsx
  ui/src/components/Header/__snapshots__/Header.test.tsx.snap
  ui/src/components/Header/index.tsx
  ui/src/config/constants.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/App/index.tsx
  ui/src/containers/Authentication/Authentication.css
  ui/src/containers/Authentication/Authentication.test.tsx
  ui/src/containers/Authentication/__snapshots__/Authentication.test.tsx.snap
  ui/src/containers/Authentication/index.tsx
  ui/src/containers/Header/Header.css
  ui/src/containers/Header/Header.test.tsx
  ui/src/containers/Header/__snapshots__/Header.test.tsx.snap
  ui/src/containers/Header/index.tsx
  ui/src/containers/UserProfile/UserProfile.css
  ui/src/containers/UserProfile/UserProfile.test.tsx
  ui/src/containers/UserProfile/index.tsx
  ui/src/react-app-env.d.ts
  ui/src/store/auth.test.ts
  ui/src/store/auth.ts
  ui/src/store/root.tsx
  ui/src/store/testdata/authentication.json
Labels: approved, lgtm, size/XL

#152 Adds readme and yaml on details page
  ui/package-lock.json
  ui/package.json
  ui/src/api/index.ts
  ui/src/api/testutil.ts
  ui/src/components/Description/Description.css
  ui/src/components/Description/Description.test.tsx
  ui/src/components/Description/index.tsx
  ui/src/components/Readme/Readme.test.tsx
  ui/src/components/Readme/__snapshots__/Readme.test.tsx.snap
  ui/src/components/Readme/index.tsx
  ui/src/components/Yaml/Yaml.test.tsx
  ui/src/components/Yaml/__snapshots__/Yaml.test.tsx.snap
  ui/src/components/Yaml/index.tsx
  ui/src/containers/Details/Details.css
  ui/src/containers/Details/Details.test.tsx
  ui/src/containers/Details/__snapshots__/Details.test.tsx.snap
  ui/src/containers/Details/index.tsx
  ui/src/store/__snapshots__/resource.test.ts.snap
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
  ui/src/store/testdata/buildah-Readme.md
  ui/src/store/testdata/buildah.yaml
Labels: approved, lgtm, size/XXL

#128 Updates Auth API to return Access and Refresh Token
  api/.env.dev
  api/design/auth.go
  api/design/type.go
  api/gen/auth/service.go
  api/gen/http/admin/client/cli.go
  api/gen/http/auth/client/encode_decode.go
  api/gen/http/auth/client/types.go
  api/gen/http/auth/server/encode_decode.go
  api/gen/http/auth/server/types.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
  api/go.mod
  api/go.sum
  api/pkg/app/app.go
  api/pkg/db/migration/202010271300_add_refresh_token_checksum_col_in_user_table.go
  api/pkg/db/migration/migration.go
  api/pkg/db/model/model.go
  api/pkg/service/admin/admin.go
  api/pkg/service/admin/admin_http_test.go
  api/pkg/service/admin/admin_test.go
  api/pkg/service/auth/auth.go
  api/pkg/service/auth/auth_http_test.go
  api/pkg/service/auth/auth_test.go
  api/pkg/service/auth/service.go
  api/pkg/service/catalog/catalog_http_test.go
  api/pkg/service/rating/rating_http_test.go
  api/pkg/testutils/utils.go
  api/pkg/token/jwt.go
  api/pkg/token/user.go
  api/test/config/env.test
  api/test/fixtures/users.yaml
Labels: approved, lgtm, size/XXL

#154 Adds few UI modification
  ui/public/favicon.ico
  ui/public/index.html
  ui/public/logo192.png
  ui/public/logo512.png
  ui/public/manifest.json
  ui/public/tekton.png
  ui/src/components/Cards/__snapshots__/Cards.test.tsx.snap
  ui/src/components/Cards/index.tsx
  ui/src/components/Description/Description.css
  ui/src/components/Description/index.tsx
  ui/src/components/TooltipDisplay/TooltipDisplay.test.tsx
  ui/src/components/TooltipDisplay/__snapshots__/TooltipDisplay.test.tsx.snap
  ui/src/components/TooltipDisplay/index.tsx
  ui/src/containers/Authentication/Authentication.css
  ui/src/containers/Authentication/index.tsx
  ui/src/containers/BasicDetails/BasicDetails.css
  ui/src/containers/BasicDetails/__snapshots__/BasicDetails.test.tsx.snap
  ui/src/containers/BasicDetails/index.tsx
  ui/src/containers/Details/__snapshots__/Details.test.tsx.snap
  ui/src/containers/Rating/Rating.css
  ui/src/containers/Rating/index.tsx
  ui/src/containers/Resources/__snapshots__/Resources.test.tsx.snap
Labels: approved, lgtm, size/XL
