Repository tektoncd/hub, pull requests merged in 2020-08, with the labels that each got.

#54 Adds readiness and liveness probe in db deployment
  api/config/12-db-deployment.yaml
Labels: approved, lgtm, size/S

#58 Add Org Column & drops Owner column from Catalog Table
  api/cmd/db/migration.go
  api/pkg/app/data.go
  api/pkg/db/initializer/initiailizer.go
  api/pkg/db/model/model.go
  api/test/fixtures/catalogs.yaml
  config.yaml
Labels: approved, lgtm, size/M

#33 Adds necessary constraints to database fields
  api/cmd/db/migration.go
  api/pkg/db/migration/202006071000_add_resource_and_resource_versions_tables.go
  api/pkg/db/migration/202006091100_add_minimum_pipeline_version_column_in_resource_version.go
  api/pkg/db/migration/202008071700_add_org_and_drop_owner_column_in_catalog.go
  api/pkg/db/migration/202008121043_add_not_null_constraint_to_resource_and_resource_version.go
  api/pkg/db/migration/migration.go
  api/pkg/db/model/model.go
  api/pkg/db/validation/validation_test.go
  api/pkg/testutils/db.go
Labels: approved, lgtm, size/L

#64 Replace LatestVersion by Version as the view issue is resolved in goa
  api/design/resource.go
  api/design/type.go
  api/gen/category/client.go
  api/gen/category/endpoints.go
  api/gen/category/service.go
  api/gen/http/category/client/cli.go
  api/gen/http/category/client/client.go
  api/gen/http/category/client/encode_decode.go
  api/gen/http/category/client/paths.go
  api/gen/http/category/client/types.go
  api/gen/http/category/server/encode_decode.go
  api/gen/http/category/server/paths.go
  api/gen/http/category/server/server.go
  api/gen/http/category/server/types.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/resource/client/cli.go
  api/gen/http/resource/client/client.go
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/client/paths.go
  api/gen/http/resource/client/types.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/paths.go
  api/gen/http/resource/server/server.go
  api/gen/http/resource/server/types.go
  api/gen/http/status/client/cli.go
  api/gen/http/status/client/client.go
  api/gen/http/status/client/encode_decode.go
  api/gen/http/status/client/paths.go
  api/gen/http/status/client/types.go
  api/gen/http/status/server/encode_decode.go
  api/gen/http/status/server/paths.go
  api/gen/http/status/server/server.go
  api/gen/http/status/server/types.go
  api/gen/http/swagger/client/client.go
  api/gen/http/swagger/client/encode_decode.go
  api/gen/http/swagger/client/paths.go
  api/gen/http/swagger/client/types.go
  api/gen/http/swagger/server/paths.go
  api/gen/http/swagger/server/server.go
  api/gen/http/swagger/server/types.go
  api/gen/resource/client.go
  api/gen/resource/endpoints.go
  api/gen/resource/service.go
  api/gen/resource/views/view.go
  api/gen/status/client.go
  api/gen/status/endpoints.go
  api/gen/status/service.go
  api/gen/swagger/client.go
  api/gen/swagger/endpoints.go
  api/gen/swagger/service.go
  api/go.mod
  api/go.sum
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/testdata/TestByTypeNameVersion_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_Http.golden
Labels: approved, lgtm, size/XXL

#67 Updates UI packages to fix the audit vulnerabilities
  ui/package-lock.json
  ui/package.json
Labels: approved, lgtm, size/XXL

#66 Update CI Script to run UI test
  test/presubmit-tests.sh
Labels: approved, lgtm, size/M
