Repository tektoncd/hub, pull requests merged in 2021-05, with the labels that each got.

#202 Adds script to create a release using Tekton
  config/00-init/01-db-secret.yaml
  config/00-init/02-db-pvc.yaml
  config/00-init/03-db-deployment.yaml
  config/00-init/04-db-service.yaml
  config/01-db/10-db-migration.yaml
  config/02-api/20-api-secret.yaml
  config/02-api/21-api-configmap.yaml
  config/02-api/22-api-deployment.yaml
  config/02-api/23-api-service.yaml
  config/03-ui/30-ui-configmap.yaml
  config/03-ui/31-ui-deployment.yaml
  config/03-ui/32-ui-service.yaml
  config/04-kubernetes/40-api-ingress.yaml
  config/04-kubernetes/41-ui-ingress.yaml
  config/04-openshift/40-api-route.yaml
  config/04-openshift/41-ui-route.yaml
  config/05-catalog-refresh-cj/50-catalog-refresh-secret.yaml
  config/05-catalog-refresh-cj/51-catalog-refresh-cronjob.yaml
  tekton/README.md
  tekton/api/golang-db-test.yaml
  tekton/api/pipeline.yaml
  tekton/release.sh
  tekton/ui/pipeline.yaml
Labels: approved, lgtm, size/XL

#257 UI: Adds a keyboard shortcut `/` to focus on search bar
  ui/package-lock.json
  ui/package.json
  ui/src/containers/Search/index.tsx
Labels: approved, lgtm, size/S

#262 Remove unwanted debug message
  api/pkg/cli/cmd/upgrade/upgrade.go
Labels: approved, lgtm, size/XS

#212 Add an ROADMAP for Hub
  ROADMAP.md
Labels: approved, lgtm, size/M
