Repository tektoncd/hub, pull requests merged in 2021-07, with the labels that each got.

#272 Update deployment doc for disconnected cluster
  docs/DEPLOYMENT.md
Labels: approved, lgtm, size/M

#270 UI: Updates the resource store based on updated resources api
  ui/src/components/Cards/index.tsx
  ui/src/containers/BasicDetails/index.tsx
  ui/src/store/__snapshots__/resource.test.ts.snap
  ui/src/store/__snapshots__/tag.test.ts.snap
  ui/src/store/category.test.ts
  ui/src/store/category.ts
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
  ui/src/store/tag.test.ts
  ui/src/store/tag.ts
  ui/src/store/testdata/resources.json
Labels: approved, lgtm, size/L

#260 Reads Hub API Server URL from '.tekton/hub-config' if present
  api/pkg/cli/cmd/root.go
  api/pkg/cli/hub/hub.go
Labels: approved, lgtm, size/M

#279 UI: Updates search to search resources by tags
  ui/src/common/params.ts
  ui/src/containers/ParseUrl/index.tsx
  ui/src/containers/Resources/index.tsx
  ui/src/containers/Search/index.tsx
  ui/src/store/__snapshots__/resource.test.ts.snap
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
  ui/src/utils/updateUrl.test.ts
  ui/src/utils/updateUrl.ts
Labels: approved, lgtm, size/L

#286 Updates the Catalog Sync to handle Categories if not present in Hub
  api/pkg/parser/catalog.go
  api/pkg/service/catalog/syncer.go
Labels: approved, lgtm, size/M

#266 Adds an ingress to redirect from Hub Preview to Hub
  config/04-kubernetes/42-hub-preview-redirect-ingress.yaml
Labels: approved, lgtm, size/S

#290 Adds a migration to remove existing Categories
  api/pkg/db/migration/202107131802_remove_existing_categories.go
  api/pkg/db/migration/migration.go
Labels: approved, lgtm, size/M

#298 UI: Deletes existing tag params before appending new tags to it
  ui/src/utils/updateUrl.ts
Labels: approved, lgtm, size/XS

#291 Adds a CRD `FrontendConfig` to redirect http --> https
  config/04-kubernetes/41-gke-hub-config.yaml
  config/04-kubernetes/41-ui-ingress.yaml
  config/04-kubernetes/42-ui-ingress.yaml
Labels: approved, lgtm, size/M

#297 Replace maze.io/x/duration to git.maze.io/go/duration
  api/go.mod
  api/go.sum
  api/pkg/app/app.go
Labels: approved, lgtm, size/XS

#280 UI: Add search tips to helps in resources search
  ui/src/common/icons.ts
  ui/src/components/Icon/index.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/Header/Header.css
  ui/src/containers/Header/Header.test.tsx
  ui/src/containers/Header/__snapshots__/Header.test.tsx.snap
  ui/src/containers/Header/index.tsx
Labels: approved, lgtm, size/L

#299 UI: Improves sentences of search hint
  ui/src/containers/Header/index.tsx
Labels: approved, lgtm, size/XS

#283 Updates the Categories List in Config
  config.yaml
Labels: approved, lgtm, size/M
