Repository tektoncd/hub, pull requests merged in 2021-09, with the labels that each got.

#293 CLI: Updates `tkn hub info task` cli command for --version flag to include deprecation info
  api/pkg/cli/cmd/info/info.go
  api/pkg/cli/cmd/info/info_test.go
  api/pkg/cli/cmd/info/testdata/TestInfoTask_WithOldVersion.golden
  api/pkg/cli/formatter/field.go
  api/pkg/cli/formatter/field_test.go
Labels: approved, lgtm, size/S

#294 CLI: Updates `tkn hub install task` cli command for --version flag to add deprecation warning
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/cmd/install/install_test.go
  api/pkg/cli/cmd/install/testdata/foo-v0.2.yaml
Labels: approved, lgtm, size/M

#305 Remove username formatting(convert lowercase) while saving the user
  api/pkg/service/auth/auth.go
  api/pkg/service/auth/auth_test.go
Labels: approved, lgtm, ok-to-test, size/M

#296 UI: Adds warning icon having a tooltip to point out the deprecation of a version
  ui/src/components/TooltipDisplay/index.tsx
  ui/src/containers/BasicDetails/__snapshots__/BasicDetails.test.tsx.snap
  ui/src/containers/BasicDetails/index.tsx
  ui/src/containers/Details/__snapshots__/Details.test.tsx.snap
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
  ui/src/store/testdata/resources.json
Labels: approved, lgtm, size/M

#317 Switch jwt libraries to golang-jwt/jwt.
  api/go.mod
  api/go.sum
  api/pkg/service/admin/admin_http_test.go
  api/pkg/service/rating/rating_http_test.go
  api/pkg/service/user/user_http_test.go
  api/pkg/token/jwt.go
  api/pkg/token/user.go
Labels: approved, lgtm, size/S

#308 UI: Fixes security vulnerability in npm dependencies
  ui/package-lock.json
  ui/package.json
  ui/src/components/Readme/__snapshots__/Readme.test.tsx.snap
Labels: approved, lgtm, size/XXL

#318 Return err if db-migration fails
  api/cmd/db/main.go
  docs/DEPLOYMENT.md
Labels: approved, lgtm, size/L

#321 Support Catalog refresh for different git providers
  api/pkg/app/data.go
  api/pkg/db/initializer/initializer.go
  api/pkg/db/migration/202109151102_add_provider_in_catalog_table.go
  api/pkg/db/migration/migration.go
  api/pkg/db/model/model.go
  api/pkg/service/catalog/syncer.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_test.go
  api/test/fixtures/catalogs.yaml
  config.yaml
Labels: approved, lgtm, size/M

#307 Add platforms support to hub cli
  api/pkg/cli/cmd/info/info.go
  api/pkg/cli/cmd/info/info_test.go
  api/pkg/cli/cmd/info/testdata/TestInfoTask_WithLatestVersion.golden
  api/pkg/cli/cmd/info/testdata/TestInfoTask_WithOldVersion.golden
  api/pkg/cli/cmd/info/testdata/TestPipelineTask_MultiLineDescription.golden
  api/pkg/cli/cmd/search/search.go
  api/pkg/cli/cmd/search/search_test.go
  api/pkg/cli/cmd/search/testdata/TestSearch_TableFormat.golden
  api/pkg/cli/formatter/field.go
  api/pkg/cli/formatter/field_test.go
  api/pkg/cli/hub/search.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestQueryWithPlatforms_Http.golden
  api/v1/design/resource.go
  api/v1/gen/http/cli/hub/cli.go
  api/v1/gen/http/openapi.json
  api/v1/gen/http/openapi.yaml
  api/v1/gen/http/openapi3.json
  api/v1/gen/http/openapi3.yaml
  api/v1/gen/http/resource/client/cli.go
  api/v1/gen/http/resource/client/encode_decode.go
  api/v1/gen/http/resource/server/encode_decode.go
  api/v1/gen/http/resource/server/types.go
  api/v1/gen/resource/service.go
  api/v1/service/resource/resource.go
  api/v1/service/resource/resource_http_test.go
  api/v1/service/resource/resource_test.go
  api/v1/service/resource/testdata/TestQueryWithPlatforms_Http.golden
Labels: approved, lgtm, size/XL

#323 Minor fixes in the search description to add platforms option
  api/design/resource.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/resource/service.go
  api/pkg/cli/cmd/search/search.go
  api/v1/design/resource.go
  api/v1/gen/http/cli/hub/cli.go
  api/v1/gen/http/openapi.json
  api/v1/gen/http/openapi.yaml
  api/v1/gen/http/openapi3.json
  api/v1/gen/http/openapi3.yaml
  api/v1/gen/resource/service.go
Labels: approved, lgtm, size/M

#285 Init e2e Test for Get Command and update presubmit.sh
  api/go.mod
  api/go.sum
  api/test/cli/cli.go
  api/test/e2e/get/get_test.go
  test/presubmit-tests.sh
Labels: approved, lgtm, size/L
