Repository tektoncd/hub, pull requests merged in 2021-04, with the labels that each got.

#227 Minor bug fix in Hub CLI info command
  api/pkg/cli/formatter/field.go
  api/pkg/cli/formatter/field_test.go
Labels: approved, lgtm, size/S

#236 UI: Fixes to rate a resource
  ui/src/containers/Rating/Rating.test.tsx
  ui/src/containers/Rating/index.tsx
Labels: approved, lgtm, size/S

#226 UI: Adds icon for catalogs
  ui/src/common/icons.ts
  ui/src/components/Cards/__snapshots__/Cards.test.tsx.snap
  ui/src/components/Icon/index.tsx
  ui/src/containers/BasicDetails/__snapshots__/BasicDetails.test.tsx.snap
  ui/src/containers/CatalogFilter/__snapshots__/CatalogFilter.test.tsx.snap
  ui/src/containers/Details/__snapshots__/Details.test.tsx.snap
  ui/src/containers/Resources/__snapshots__/Resources.test.tsx.snap
  ui/src/store/catalog.test.ts
  ui/src/store/catalog.ts
Labels: approved, lgtm, size/L

#237 CLI: Improves error message for search command
  api/pkg/cli/cmd/search/search.go
  api/pkg/cli/cmd/search/search_test.go
Labels: approved, lgtm, size/XS

#214 UI: Adds selected filters in the url as a query parameter
  ui/src/common/params.ts
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/App/index.tsx
  ui/src/containers/ParseUrl/ParseUrl.test.tsx
  ui/src/containers/ParseUrl/index.tsx
  ui/src/containers/Resources/__snapshots__/Resources.test.tsx.snap
  ui/src/containers/Resources/index.tsx
  ui/src/containers/Search/index.tsx
  ui/src/store/catalog.test.ts
  ui/src/store/catalog.ts
  ui/src/store/category.test.ts
  ui/src/store/category.ts
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
  ui/src/utils/updateUrl.test.ts
  ui/src/utils/updateUrl.ts
Labels: approved, lgtm, size/L

#219 Api to get resources from one or multiple catalogs
  api/design/resource.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/resource/client/cli.go
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/types.go
  api/gen/resource/service.go
  api/pkg/service/resource/resource.go
  api/pkg/shared/resource/resource.go
  api/pkg/shared/resource/resource_test.go
  api/v1/design/resource.go
  api/v1/gen/http/cli/hub/cli.go
  api/v1/gen/http/openapi.json
  api/v1/gen/http/openapi.yaml
  api/v1/gen/http/openapi3.json
  api/v1/gen/http/openapi3.yaml
  api/v1/gen/http/resource/client/cli.go
  api/v1/gen/http/resource/client/encode_decode.go
  api/v1/gen/http/resource/server/encode_decode.go
  api/v1/gen/http/resource/server/types.go
  api/v1/gen/resource/service.go
  api/v1/service/resource/resource.go
Labels: approved, lgtm, size/L

#229 CLI: Respect pipelines version in CLI subcommands
  api/go.mod
  api/go.sum
  api/pkg/cli/cmd/downgrade/downgrade.go
  api/pkg/cli/cmd/downgrade/downgrade_test.go
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/cmd/reinstall/reinstall.go
  api/pkg/cli/cmd/reinstall/reinstall_test.go
  api/pkg/cli/cmd/upgrade/upgrade.go
  api/pkg/cli/cmd/upgrade/upgrade_test.go
  api/pkg/cli/installer/action.go
Labels: approved, lgtm, size/XL

#233 Adds deployment config files for Hub Swagger UI
  config/06-swagger/00-config/00-swagger-configmap.yaml
  config/06-swagger/00-config/01-swagger-deployment.yaml
  config/06-swagger/00-config/02-swagger-service.yaml
  config/06-swagger/01-kubernetes/01-swagger-ingress.yaml
  config/06-swagger/01-openshift/01-swagger-route.yaml
Labels: approved, lgtm, size/L

#241 Adds examples to attribute fields
  api/design/admin.go
  api/design/types/type.go
  api/gen/http/admin/client/cli.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
Labels: approved, lgtm, size/XL

#243 UI: Scroll to top of home page when users click on the Hub logo
  ui/src/common/scrollToTop.test.ts
  ui/src/common/scrollToTop.ts
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/Details/index.tsx
  ui/src/containers/Header/__snapshots__/Header.test.tsx.snap
  ui/src/containers/Header/index.tsx
Labels: approved, lgtm, size/M

#231 UI: Adds user informations after authentication
  ui/src/api/index.ts
  ui/src/api/testutil.ts
  ui/src/containers/UserProfile/UserProfile.css
  ui/src/containers/UserProfile/UserProfile.test.tsx
  ui/src/containers/UserProfile/index.tsx
  ui/src/store/auth.test.ts
  ui/src/store/auth.ts
  ui/src/store/testdata/userInfo.json
Labels: approved, lgtm, size/L

#221 UI: Updates Catalog store
  config/03-ui/30-ui-configmap.yaml
  config/03-ui/31-ui-deployment.yaml
  ui/image/start.sh
  ui/public/config.js
  ui/src/api/index.ts
  ui/src/api/testutil.ts
  ui/src/components/Cards/Cards.test.tsx
  ui/src/components/Filter/Filter.test.tsx
  ui/src/config/constant.d.ts
  ui/src/config/constants.tsx
  ui/src/containers/CatalogFilter/__snapshots__/CatalogFilter.test.tsx.snap
  ui/src/containers/CatalogFilter/index.tsx
  ui/src/store/__snapshots__/catalog.test.ts.snap
  ui/src/store/__snapshots__/resource.test.ts.snap
  ui/src/store/catalog.test.ts
  ui/src/store/catalog.ts
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
  ui/src/store/root.tsx
  ui/src/store/testdata/catalogs.json
Labels: approved, lgtm, size/L

#247 Fixes the swagger API by copying it to a custom path
  api/Dockerfile
  api/design/swagger.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/swagger/server/server.go
  api/v1/design/swagger.go
  api/v1/gen/http/openapi.json
  api/v1/gen/http/openapi.yaml
  api/v1/gen/http/openapi3.json
  api/v1/gen/http/openapi3.yaml
  api/v1/gen/http/swagger/server/server.go
Labels: approved, lgtm, size/M

#245 CLI: Add command to check upgrades
  api/go.mod
  api/go.sum
  api/pkg/cli/cmd/check_upgrade/check_upgrade_test.go
  api/pkg/cli/cmd/check_upgrade/check_uprade.go
  api/pkg/cli/cmd/check_upgrade/testdata/TestNoUpdateAvailable.golden
  api/pkg/cli/cmd/check_upgrade/testdata/TestNoUpdateAvailable_TaskNotInstalledViaHubCLI.golden
  api/pkg/cli/cmd/check_upgrade/testdata/TestUpdateAvailable.golden
  api/pkg/cli/cmd/check_upgrade/testdata/TestUpdateAvailable_PipelinesUnknown.golden
  api/pkg/cli/cmd/check_upgrade/testdata/TestUpdateAvailable_WithSkippedTasks.golden
  api/pkg/cli/cmd/check_upgrade/testdata/TestUpdateAvailable_WithSkippedTasks_PipelinesUnknown.golden
  api/pkg/cli/cmd/info/info_test.go
  api/pkg/cli/cmd/root.go
  api/pkg/cli/formatter/field.go
  api/pkg/cli/formatter/field_test.go
  api/pkg/cli/hub/get_resource.go
  api/pkg/cli/hub/get_resource_test.go
  api/pkg/cli/installer/action.go
  api/pkg/cli/installer/action_test.go
  api/pkg/cli/installer/kube_action.go
Labels: approved, lgtm, size/XL

#256 UI: Fixes UI start script
  ui/image/start.sh
Labels: approved, lgtm, size/M
