Repository tektoncd/hub, pull requests merged in 2021-06, with the labels that each got.

#261 UI: Updates year to current year in the footer
  ui/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  ui/src/components/Footer/index.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
Labels: approved, lgtm, size/S

#253 Update Deployment Docs
  docs/DEPLOYMENT.md
Labels: approved, lgtm, size/L

#268 Updates the Swagger API route
  config/06-swagger/00-config/00-swagger-configmap.yaml
  swagger/public/config.js
  swagger/src/config/constants.tsx
Labels: approved, lgtm, size/XS

#249 Api to fetch catalog errors
  api/design/catalog.go
  api/design/types/type.go
  api/gen/catalog/client.go
  api/gen/catalog/endpoints.go
  api/gen/catalog/service.go
  api/gen/http/catalog/client/cli.go
  api/gen/http/catalog/client/client.go
  api/gen/http/catalog/client/encode_decode.go
  api/gen/http/catalog/client/paths.go
  api/gen/http/catalog/client/types.go
  api/gen/http/catalog/server/encode_decode.go
  api/gen/http/catalog/server/paths.go
  api/gen/http/catalog/server/server.go
  api/gen/http/catalog/server/types.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
  api/pkg/service/catalog/catalog.go
  api/pkg/service/catalog/catalog_http_test.go
  api/pkg/service/catalog/catalog_test.go
  api/pkg/service/catalog/testdata/TestCatalogError_Http.golden
  api/pkg/service/catalog/testdata/TestCatalogError_HttpHavingNoError.golden
  api/test/fixtures/catalog_errors.yaml
Labels: approved, lgtm, size/XXL

#276 Update Readme
  README.md
Labels: approved, lgtm, size/M

#274 Update the Catalog Errors order
  api/pkg/service/catalog/catalog.go
  api/pkg/service/catalog/catalog_test.go
  api/pkg/service/catalog/testdata/TestCatalogError_Http.golden
Labels: approved, lgtm, size/M

#263 UI: Improves url link in the resource README
  ui/src/components/Description/index.tsx
Labels: approved, lgtm, size/M

#259 UI: Fixes search bar and debounce for search
  ui/package-lock.json
  ui/package.json
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/Header/__snapshots__/Header.test.tsx.snap
  ui/src/containers/Search/__snapshots__/Search.test.tsx.snap
  ui/src/containers/Search/index.tsx
  ui/src/utils/useDebounce.test.tsx
  ui/src/utils/useDebounce.tsx
Labels: approved, lgtm, size/L

#265 Adds interactive mode for info command
  api/go.mod
  api/go.sum
  api/pkg/cli/cmd/info/info.go
  api/pkg/cli/cmd/info/info_test.go
  api/pkg/cli/cmd/info/testdata/TestInfoPipeline_Description.golden
  api/pkg/cli/cmd/info/testdata/TestInfoPipeline_WithVersion.golden
  api/pkg/cli/cmd/info/testdata/TestInfoTask_WithLatestVersion.golden
  api/pkg/cli/cmd/info/testdata/TestInfoTask_WithOldVersion.golden
  api/pkg/cli/cmd/info/testdata/TestInfoTask_WithoutVersion.golden
  api/pkg/cli/cmd/info/testdata/TestPipelineTask_MultiLineDescription.golden
  api/pkg/cli/hub/get_catalog.go
  api/pkg/cli/hub/get_catalog_test.go
  api/pkg/cli/hub/get_resource.go
  api/pkg/cli/hub/hub.go
  api/pkg/cli/hub/search.go
  api/pkg/cli/select_options/select_options.go
  api/pkg/cli/select_options/select_options_test.go
  api/pkg/cli/test/prompt/prompt.go
Labels: approved, lgtm, size/XXL

#267 UI: Updates the category store based on updated categories api
  ui/src/store/__snapshots__/category.test.ts.snap
  ui/src/store/category.test.ts
  ui/src/store/category.ts
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
  ui/src/store/testdata/categories.json
Labels: approved, lgtm, size/L

#278 Fetch installed tekton component version from ConfigMap
  api/pkg/cli/test/helpers.go
  api/pkg/cli/version/version.go
  api/pkg/cli/version/version_test.go
Labels: approved, lgtm, size/M

#271 Adds interactive mode for `get` command
  api/pkg/cli/cmd/get/get.go
  api/pkg/cli/cmd/get/get_test.go
  api/pkg/cli/cmd/get/task.go
  api/pkg/cli/cmd/get/task_test.go
  api/pkg/cli/cmd/get/testdata/TestGetResource_WithNewVersion.golden
  api/pkg/cli/cmd/get/testdata/TestGetResource_WithOldVersion.golden
  api/pkg/cli/cmd/get/testdata/TestGetTask_WithNewVersion.golden
  api/pkg/cli/cmd/get/testdata/TestGetTask_WithoutVersion.golden
  api/pkg/cli/cmd/get/testdata/pipeline-mango-v0.2.yaml
Labels: approved, lgtm, size/XL
