Repository tektoncd/hub, pull requests merged in 2021-03, with the labels that each got.

#193 Updates adding users & scopes from config files
  api/pkg/db/initializer/initializer.go
  api/pkg/service/admin/admin_http_test.go
  api/pkg/service/auth/auth.go
  api/pkg/service/auth/auth_test.go
  api/test/config/config.yaml
  api/test/fixtures/user_scopes.yaml
  api/test/fixtures/users.yaml
Labels: approved, lgtm, size/L

#203 UI: Minor fixes for updating the packages and fixing lint
  ui/package-lock.json
  ui/src/utils/useDebounce.test.tsx
Labels: approved, lgtm, size/S

#197 UI: Adds a button to clear all selected filters
  ui/src/containers/Resources/Resources.test.tsx
  ui/src/containers/Resources/index.tsx
  ui/src/containers/Search/index.tsx
  ui/src/containers/SortDropDown/index.tsx
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
Labels: approved, lgtm, size/L

#195 UI: Validates resource details page url's params
  ui/package-lock.json
  ui/src/common/icons.ts
  ui/src/components/Icon/index.tsx
  ui/src/components/PageNotFound/PageNotFound.css
  ui/src/components/PageNotFound/PageNotFound.test.tsx
  ui/src/components/PageNotFound/__snapshots__/PageNotFound.test.tsx.snap
  ui/src/components/PageNotFound/index.tsx
  ui/src/containers/Details/Details.test.tsx
  ui/src/containers/Details/index.tsx
Labels: approved, lgtm, size/XXL

#176 UI:Updates the access and refresh token to keep user logged in
  ui/src/api/index.ts
  ui/src/api/testutil.ts
  ui/src/common/testutils.ts
  ui/src/containers/Header/Header.test.tsx
  ui/src/containers/Header/index.tsx
  ui/src/containers/UserProfile/index.tsx
  ui/src/store/auth.test.ts
  ui/src/store/auth.ts
  ui/src/store/testdata/access_token.json
  ui/src/store/testdata/refresh_token.json
Labels: approved, lgtm, size/L

#205 Handles the refresh token and access token time interval
  ui/src/containers/UserProfile/index.tsx
Labels: approved, lgtm, size/M

#210 Adds API policy doc
  docs/API_POLICY.md
Labels: approved, lgtm, size/M

#194 Updates catalog branch from master to main
  .github/pull_request_template.md
  CONTRIBUTING.md
  README.md
  api/design/types/type.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/pkg/db/migration/202102171333_update_catalog_branch_to_main.go
  api/pkg/db/migration/migration.go
  api/v1/gen/http/openapi.json
  api/v1/gen/http/openapi.yaml
  api/v1/gen/http/openapi3.json
  api/v1/gen/http/openapi3.yaml
  config.yaml
  config/02-api/21-api-configmap.yaml
Labels: approved, lgtm, size/XL

#218 Update the resource url in db during catalog refresh
  api/pkg/service/catalog/syncer.go
Labels: approved, lgtm, size/XS

#204 Updates catalog refresh API to refresh by its name
  api/design/catalog.go
  api/design/types/type.go
  api/gen/catalog/service.go
  api/gen/catalog/views/view.go
  api/gen/http/admin/client/cli.go
  api/gen/http/catalog/client/cli.go
  api/gen/http/catalog/client/encode_decode.go
  api/gen/http/catalog/client/paths.go
  api/gen/http/catalog/client/types.go
  api/gen/http/catalog/server/encode_decode.go
  api/gen/http/catalog/server/paths.go
  api/gen/http/catalog/server/server.go
  api/gen/http/catalog/server/types.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/pkg/service/catalog/catalog.go
  api/pkg/service/catalog/catalog_http_test.go
  api/pkg/service/catalog/catalog_test.go
  config/05-catalog-refresh-cj/51-catalog-refresh-cronjob.yaml
Labels: approved, lgtm, size/XXL

#209 Adds doc defining steps to add new catalog in Hub
  docs/ADD_NEW_CATALOG.md
Labels: approved, lgtm, size/S

#213 Adds multi catalog support for UI
  ui/src/components/Description/Description.test.tsx
  ui/src/components/Description/index.tsx
  ui/src/containers/BasicDetails/BasicDetails.test.tsx
  ui/src/containers/BasicDetails/index.tsx
  ui/src/containers/Details/__snapshots__/Details.test.tsx.snap
  ui/src/containers/Details/index.tsx
  ui/src/store/__snapshots__/resource.test.ts.snap
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
Labels: approved, lgtm, size/XL

#220 UI: Add `tkn cli` command to install task from UI
  ui/src/containers/BasicDetails/index.tsx
  ui/src/store/resource.test.ts
  ui/src/store/resource.ts
Labels: approved, lgtm, size/M

#200 CLI: install resource on basis of pipelines installed
  api/go.sum
  api/pkg/cli/cmd/downgrade/downgrade_test.go
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/cmd/install/install_test.go
  api/pkg/cli/cmd/reinstall/reinstall_test.go
  api/pkg/cli/cmd/upgrade/upgrade_test.go
  api/pkg/cli/installer/action.go
  api/pkg/cli/installer/config.go
  api/pkg/cli/test/helpers.go
  api/pkg/cli/version/version.go
  api/pkg/cli/version/version_test.go
Labels: approved, lgtm, size/XL

#223 Adds catalog name in hub cli search command
  api/pkg/cli/cmd/search/search.go
  api/pkg/cli/cmd/search/search_test.go
  api/pkg/cli/cmd/search/testdata/TestSearch_JSONFormat.golden
  api/pkg/cli/cmd/search/testdata/TestSearch_TableFormat.golden
  api/pkg/cli/formatter/field.go
  api/pkg/cli/formatter/field_test.go
Labels: approved, lgtm, size/M

#215 API to refresh all catalogs
  api/design/catalog.go
  api/gen/catalog/client.go
  api/gen/catalog/endpoints.go
  api/gen/catalog/service.go
  api/gen/http/admin/client/cli.go
  api/gen/http/catalog/client/cli.go
  api/gen/http/catalog/client/client.go
  api/gen/http/catalog/client/encode_decode.go
  api/gen/http/catalog/client/paths.go
  api/gen/http/catalog/client/types.go
  api/gen/http/catalog/server/encode_decode.go
  api/gen/http/catalog/server/paths.go
  api/gen/http/catalog/server/server.go
  api/gen/http/catalog/server/types.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
  api/pkg/service/catalog/catalog.go
  api/pkg/service/catalog/catalog_http_test.go
  api/pkg/service/catalog/catalog_test.go
  api/pkg/service/catalog/syncer.go
Labels: approved, lgtm, size/XXL

#225 Fixes catalog refresh tests and lint errors
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/formatter/field.go
  api/pkg/service/admin/admin.go
  api/pkg/service/catalog/catalog.go
  api/test/fixtures/sync_jobs.yaml
Labels: approved, lgtm, size/M
