Repository tektoncd/hub, pull requests merged in 2021-02, with the labels that each got.

#179 README: Remove repo migration notes
  README.md
Labels: approved, lgtm, size/XS

#180 bump deps - k8s dep goes to v0.19.7
  api/go.mod
  api/go.sum
Labels: approved, lgtm, ok-to-test, size/XXL

#181 Updates Deployment doc
  api/config/99-post-deploy/35-catalog-refresh-cronjob.yaml
  docs/DEPLOYMENT.md
Labels: approved, lgtm, size/L

#183 Replaced preview url with non-preview url
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#184 Adds Dockerfiles for API and Db migration & Update deployment flow
  api/.ko.yaml
  api/Dockerfile
  api/db.Dockerfile
  config/00-init/00-namespace.yaml
  config/00-init/01-db-secret.yaml
  config/00-init/02-db-pvc.yaml
  config/00-init/03-db-deployment.yaml
  config/00-init/04-db-service.yaml
  config/01-db/10-db-migration.yaml
  config/02-api/20-api-secret.yaml
  config/02-api/21-api-configmap.yaml
  config/02-api/22-api-deployment.yaml
  config/02-api/23-api-service.yaml
  config/03-ui/30-ui-configmap.yaml
  config/03-ui/31-ui-deployment.yaml
  config/03-ui/32-ui-service.yaml
  config/04-kubernetes/40-api-ingress.yaml
  config/04-kubernetes/41-ui-ingress.yaml
  config/04-openshift/40-api-route.yaml
  config/04-openshift/41-ui-route.yaml
  config/05-catalog-refresh-cj/50-catalog-refresh-secret.yaml
  config/05-catalog-refresh-cj/51-catalog-refresh-cronjob.yaml
  docs/DEPLOYMENT.md
  ui/config/00-namespace.yaml
Labels: approved, lgtm, size/L

#187 UI: Fixes resource cards margin
  ui/src/components/Cards/Cards.css
Labels: approved, lgtm, size/XS

#189 Adds Hub logo in Readme
  README.md
Labels: approved, lgtm, size/XS

#192 Adds Hub logo in UI
  ui/src/assets/logo/logo.png
Labels: approved, lgtm, size/XS

#160 UI:Updates packages that have vulnerability
  ui/.eslintrc.json
  ui/.gitignore
  ui/package-lock.json
  ui/package.json
  ui/src/config/constant.d.ts
  ui/src/config/constants.tsx
  ui/src/containers/App/App.test.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/Authentication/Authentication.test.tsx
  ui/src/containers/Resources/index.tsx
  ui/tsconfig.json
Labels: approved, lgtm, size/XXL

#191 Fixes CLI tests
  api/pkg/cli/test/helpers.go
Labels: approved, lgtm, size/XS

#136 API to refresh access token api for user
  api/cmd/api/http.go
  api/cmd/api/main.go
  api/design/api.go
  api/design/types/type.go
  api/design/user.go
  api/gen/admin/endpoints.go
  api/gen/catalog/endpoints.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/user/client/cli.go
  api/gen/http/user/client/client.go
  api/gen/http/user/client/encode_decode.go
  api/gen/http/user/client/paths.go
  api/gen/http/user/client/types.go
  api/gen/http/user/server/encode_decode.go
  api/gen/http/user/server/paths.go
  api/gen/http/user/server/server.go
  api/gen/http/user/server/types.go
  api/gen/rating/endpoints.go
  api/gen/user/client.go
  api/gen/user/endpoints.go
  api/gen/user/service.go
  api/pkg/service/user/user.go
  api/pkg/service/user/user_http_test.go
  api/pkg/service/user/user_test.go
  api/test/fixtures/users.yaml
Labels: approved, lgtm, size/XXL

#185 UI: Improves search
  ui/package-lock.json
  ui/package.json
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/Header/__snapshots__/Header.test.tsx.snap
  ui/src/containers/Search/Search.test.tsx
  ui/src/containers/Search/index.tsx
  ui/src/utils/useDebounce.test.tsx
  ui/src/utils/useDebounce.tsx
Labels: approved, lgtm, size/XXL

#132 API to get new refresh token for user
  api/design/types/type.go
  api/design/user.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/user/client/cli.go
  api/gen/http/user/client/client.go
  api/gen/http/user/client/encode_decode.go
  api/gen/http/user/client/paths.go
  api/gen/http/user/client/types.go
  api/gen/http/user/server/encode_decode.go
  api/gen/http/user/server/paths.go
  api/gen/http/user/server/server.go
  api/gen/http/user/server/types.go
  api/gen/user/client.go
  api/gen/user/endpoints.go
  api/gen/user/service.go
  api/pkg/service/user/user.go
  api/pkg/service/user/user_http_test.go
  api/pkg/service/user/user_test.go
Labels: approved, lgtm, size/XXL

#201 Drop Chmouel's cobra fork and use upstream one
  api/go.mod
  api/go.sum
Labels: approved, lgtm, size/S
