Repository tektoncd/hub, pull requests merged in 2021-01, with the labels that each got.

#156 Make Alert Component Generic and better Alert Messages
  ui/src/api/index.ts
  ui/src/components/AlertDisplay/AlertDisplay.css
  ui/src/components/AlertDisplay/AlertDisplay.test.tsx
  ui/src/components/AlertDisplay/__snapshots__/AlertDisplay.test.tsx.snap
  ui/src/components/AlertDisplay/index.tsx
  ui/src/containers/Authentication/Authentication.css
  ui/src/containers/Authentication/index.tsx
  ui/src/containers/Header/Header.test.tsx
  ui/src/containers/Rating/Rating.css
  ui/src/containers/Rating/Rating.test.tsx
  ui/src/containers/Rating/index.tsx
  ui/src/store/auth.test.ts
  ui/src/store/auth.ts
Labels: approved, lgtm, size/L

#157 Add Access and Refresh expiry time in secrets
  api/config/00-config/31-api-secret.yaml
  api/config/31-api-deployment.yaml
  docs/DEPLOYMENT.md
Labels: approved, lgtm, size/M

#158 UI:Modifies style of resource Icon on details page
  ui/src/containers/BasicDetails/BasicDetails.css
  ui/src/containers/BasicDetails/__snapshots__/BasicDetails.test.tsx.snap
  ui/src/containers/BasicDetails/index.tsx
  ui/src/containers/Details/__snapshots__/Details.test.tsx.snap
Labels: approved, lgtm, size/L

#161 Fix Scroll issue and lint errors
  ui/src/containers/Authentication/index.tsx
  ui/src/containers/Details/index.tsx
  ui/src/store/auth.test.ts
Labels: approved, lgtm, size/S

#162 UI: Adds EmptyState with title `No Resource Found`
  ui/src/containers/Resources/Resources.css
  ui/src/containers/Resources/Resources.test.tsx
  ui/src/containers/Resources/index.tsx
Labels: approved, lgtm, size/M

#164 Fix moment date tests
  ui/src/components/Cards/Cards.test.tsx
  ui/src/containers/Resources/Resources.test.tsx
Labels: approved, lgtm, size/S

#165 UI: Modifies style of Github login button
  ui/src/containers/Authentication/Authentication.css
Labels: approved, lgtm, size/XS

#166 Updates hub config for new tags added in Catalog
  config.yaml
Labels: approved, lgtm, size/M

#167 Updates categories and tags in config manifest
  config.yaml
Labels: approved, lgtm, size/XS

#163 Adds v1 support to APIs
  api/design/api.go
  api/design/category.go
  api/design/resource.go
  api/gen/http/category/client/paths.go
  api/gen/http/category/server/paths.go
  api/gen/http/category/server/server.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/resource/client/paths.go
  api/gen/http/resource/server/paths.go
  api/gen/http/resource/server/server.go
  api/pkg/service/category/category_http_test.go
  api/pkg/service/category/testdata/TestCategories_List_V1_Http.golden
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/testdata/TestByCatalogKindNameVersion_V1_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_V1_Http.golden
  api/pkg/service/resource/testdata/TestByID_V1_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_V1_Http.golden
  api/pkg/service/resource/testdata/TestList_V1_Http.golden
  api/pkg/service/resource/testdata/TestQuery_V1_Http.golden
  api/pkg/service/resource/testdata/TestVersionsByID_V1_Http.golden
Labels: approved, lgtm, size/XXL

#171 Update Deployment and Development docs
  docs/DEPLOYMENT.md
  docs/DEVELOPMENT.md
Labels: approved, lgtm, size/L

#173 Adds table in markdown
  ui/package-lock.json
  ui/package.json
  ui/src/components/Description/Description.css
  ui/src/components/Description/index.tsx
Labels: approved, lgtm, size/L
