Repository tektoncd/hub, pull requests merged in 2021-08, with the labels that each got.

#301 Refeshes all tables in Hub DB
  api/pkg/db/migration/202105311800_remove_categoryid_column_and_category_tag_constraints_from_tag_table.go
  api/pkg/db/migration/202107291608_refresh_all_tables.go
  api/pkg/db/migration/migration.go
  api/test/fixtures/sync_jobs.yaml
Labels: approved, lgtm, size/L

#304 Handles the last value of the table while refreshing all tables
  api/pkg/db/migration/202107291608_refresh_all_tables.go
Labels: approved, lgtm, size/L

#302 Updates the Categories List
  config.yaml
Labels: approved, lgtm, size/M

#309 Removes namespace from swagger config files to maintain consistency
  config/06-swagger/00-config/00-swagger-configmap.yaml
  config/06-swagger/00-config/01-swagger-deployment.yaml
  config/06-swagger/00-config/02-swagger-service.yaml
  config/06-swagger/01-kubernetes/01-swagger-ingress.yaml
  config/06-swagger/01-openshift/01-swagger-route.yaml
Labels: approved, size/XS, lgtm

#310 Adds docs to define steps to add new categories in Hub
  docs/ADD_NEW_CATEGORY.md
Labels: approved, lgtm, size/S

#284 Parses deprecation info from resources and update the API's Response
  api/design/types/type.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/client/types.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/types.go
  api/gen/resource/service.go
  api/gen/resource/views/view.go
  api/pkg/cli/cmd/search/search_test.go
  api/pkg/cli/cmd/search/testdata/TestSearch_JSONFormat.golden
  api/pkg/db/migration/202106282200_add_deprecated_col_in_resource_version_table.go
  api/pkg/db/migration/migration.go
  api/pkg/db/model/model.go
  api/pkg/parser/catalog.go
  api/pkg/service/catalog/syncer.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestDeprecationByVersionID_Http.golden
  api/pkg/service/resource/testdata/TestLatestVersionDeprecationByID_Http.golden
  api/pkg/service/resource/testdata/TestList_Http_NoLimit.golden
  api/test/fixtures/resource_versions.yaml
  api/v1/gen/http/openapi.json
  api/v1/gen/http/openapi.yaml
  api/v1/gen/http/openapi3.json
  api/v1/gen/http/openapi3.yaml
  api/v1/gen/http/resource/client/encode_decode.go
  api/v1/gen/http/resource/client/types.go
  api/v1/gen/http/resource/server/encode_decode.go
  api/v1/gen/http/resource/server/types.go
  api/v1/gen/resource/service.go
  api/v1/gen/resource/views/view.go
  api/v1/service/resource/resource.go
  api/v1/service/resource/resource_http_test.go
  api/v1/service/resource/resource_test.go
  api/v1/service/resource/testdata/TestDeprecationByVersionID_Http.golden
  api/v1/service/resource/testdata/TestLatestVersionDeprecationByID_Http.golden
  api/v1/service/resource/testdata/TestList_Http_NoLimit.golden
Labels: approved, lgtm, size/XL
