Repository tektoncd/hub, pull requests merged in 2022-04, with the labels that each got.

#403 Adds resource requests and limits for api, db and ui
  config/00-init/03-db-deployment.yaml
  config/02-api/22-api-deployment.yaml
  config/03-ui/31-ui-deployment.yaml
Labels: approved, lgtm, size/S

#400 Adds return type to the UI store's view
  ui/src/components/Description/index.tsx
  ui/src/containers/BasicDetails/index.tsx
  ui/src/containers/Details/index.tsx
  ui/src/containers/ParseUrl/index.tsx
  ui/src/containers/Rating/index.tsx
  ui/src/containers/Resources/index.tsx
  ui/src/store/catalog.ts
  ui/src/store/category.ts
  ui/src/store/kind.ts
  ui/src/store/platform.ts
  ui/src/store/root.tsx
Labels: approved, lgtm, size/M

#431 Run update before install
  test/presubmit-tests.sh
Labels: approved, size/XS, lgtm

#486 Bump mobx from 5.15.6 to 6.5.0 and mobx-state-tree from 3.17.3 to 5.1.3 in /ui
  ui/package-lock.json
  ui/package.json
Labels: approved, lgtm, size/M

#493 Split the nginx.conf by separating locations directive
  images/ui.Dockerfile
  ui/image/location.locations
  ui/image/nginx.conf
Labels: approved, lgtm, size/S
