Repository tektoncd/hub, pull requests merged in 2022-10, with the labels that each got.

#662 use multi-arch postgres image
  config/00-init/03-db-deployment.yaml
Labels: approved, size/XS, lgtm

#656 Add Multi-arch support for tekton-hub
  images/api.Dockerfile
  images/db.Dockerfile
  images/ui.Dockerfile
  release.sh
  release/RELEASE.md
Labels: approved, lgtm, ok-to-test, size/S

#686 Fix API tests
  api/pkg/auth/service/auth.go
Labels: approved, size/XS, lgtm

#687 Fix validation tests
  api/pkg/db/validation/validation_test.go
  api/pkg/user/service/user.go
  test/presubmit-tests.sh
Labels: approved, lgtm, size/S

#692 Add "type" flag to CLI
  api/pkg/cli/app/app.go
  api/pkg/cli/cmd/check_upgrade/check_uprade.go
  api/pkg/cli/cmd/downgrade/downgrade.go
  api/pkg/cli/cmd/get/get.go
  api/pkg/cli/cmd/get/get_test.go
  api/pkg/cli/cmd/info/info.go
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/cmd/reinstall/reinstall.go
  api/pkg/cli/cmd/root.go
  api/pkg/cli/cmd/search/search.go
  api/pkg/cli/cmd/search/search_test.go
  api/pkg/cli/cmd/upgrade/upgrade.go
  api/pkg/cli/hub/get_catalog.go
  api/pkg/cli/hub/get_catalog_test.go
  api/pkg/cli/hub/get_resource.go
  api/pkg/cli/hub/get_resource_version.go
  api/pkg/cli/hub/hub.go
  api/pkg/cli/hub/hub_test.go
  api/pkg/cli/hub/search.go
  api/pkg/cli/test/config.go
Labels: approved, lgtm, size/L
