Repository tektoncd/hub, pull requests merged in 2022-09, with the labels that each got.

#639 Removes `react-test-renderer` npm package
  ui/package-lock.json
  ui/package.json
  ui/src/components/Background/Background.test.tsx
  ui/src/components/Background/__snapshots__/Background.test.tsx.snap
  ui/src/components/Footer/Footer.test.tsx
  ui/src/components/Footer/__snapshots__/Footer.test.tsx.snap
Labels: approved, lgtm, size/L

#657 Updates release scripts to create new release branch
  release.sh
Labels: approved, lgtm, size/S

#658 Disables search in the sort by dropdown
  ui/src/components/LeftPane/__snapshots__/LeftPane.test.tsx.snap
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/SortDropDown/index.tsx
Labels: approved, lgtm, size/M

#660 Fix background color for Footer
  ui/src/components/Footer/Footer.css
Labels: approved, size/XS, lgtm
