Repository tektoncd/hub, pull requests merged in 2022-01, with the labels that each got.

#350 Update UI snapshots to match the current year
  ui/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
Labels: approved, size/XS, lgtm

#349 Update deployment configs with latest envs
  config/02-api/20-api-secret.yaml
  config/02-api/22-api-deployment.yaml
  config/03-ui/30-ui-configmap.yaml
  config/03-ui/31-ui-deployment.yaml
Labels: approved, lgtm, size/M

#352 Change `user_name` to `userName` in /info API
  api/pkg/user/app/app.go
Labels: approved, size/XS, lgtm

#335 Adds a script to generate release yamls
  release.sh
  release/RELEASE.md
Labels: approved, lgtm, size/L

#306 Updates auth UI to supports multiple auth provider
  ui/image/start.sh
  ui/public/config.js
  ui/src/api/index.ts
  ui/src/api/testutil.ts
  ui/src/common/icons.ts
  ui/src/common/params.ts
  ui/src/components/Icon/Icon.test.tsx
  ui/src/components/Icon/__snapshots__/Icon.test.tsx.snap
  ui/src/components/Icon/index.tsx
  ui/src/config/constant.d.ts
  ui/src/config/constants.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/App/index.tsx
  ui/src/containers/Authentication/Authentication.css
  ui/src/containers/Authentication/Authentication.test.tsx
  ui/src/containers/Authentication/__snapshots__/Authentication.test.tsx.snap
  ui/src/containers/Authentication/index.tsx
  ui/src/containers/Header/Header.css
  ui/src/containers/Header/Header.test.tsx
  ui/src/containers/Header/__snapshots__/Header.test.tsx.snap
  ui/src/containers/Header/index.tsx
  ui/src/containers/ParseUrl/index.tsx
  ui/src/containers/Rating/index.tsx
  ui/src/containers/UserProfile/index.tsx
  ui/src/store/__snapshots__/provider.test.ts.snap
  ui/src/store/auth.test.ts
  ui/src/store/auth.ts
  ui/src/store/provider.test.ts
  ui/src/store/provider.ts
  ui/src/store/root.tsx
  ui/src/store/testdata/provider.json
  ui/src/store/testdata/userInfo.json
  ui/src/utils/updateUrl.ts
Labels: approved, lgtm, size/XL

#355 Updates the CONFIG_JS variable in start.sh by making it parameterized
  ui/image/start.sh
Labels: approved, size/XS, lgtm

#358 Update Hub CLI to use `/v1` api's as preview api will be removed
  api/pkg/cli/hub/get_resource.go
  api/pkg/cli/hub/get_resource_test.go
  api/pkg/cli/hub/get_resource_version.go
  api/pkg/cli/hub/get_resource_version_test.go
  api/pkg/cli/hub/search.go
  api/pkg/cli/hub/search_test.go
Labels: approved, lgtm, size/S

#359 Handles user data username case formatting
  api/pkg/auth/service/service.go
Labels: approved, size/XS, lgtm
