Repository tektoncd/hub, pull requests merged in 2022-02, with the labels that each got.

#363 Revert "Removes hub preview APIs for resources"
  api/cmd/api/http.go
  api/cmd/api/main.go
  api/design/api.go
  api/design/resource.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
  api/gen/http/resource/client/cli.go
  api/gen/http/resource/client/client.go
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/client/paths.go
  api/gen/http/resource/client/types.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/paths.go
  api/gen/http/resource/server/server.go
  api/gen/http/resource/server/types.go
  api/gen/resource/client.go
  api/gen/resource/endpoints.go
  api/gen/resource/service.go
  api/gen/resource/views/view.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestByCatalogKindNameVersion_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindNameVersion_V1_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_CompatibleVersion_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_V1_Http.golden
  api/pkg/service/resource/testdata/TestByEnterpriseCatalogKindName_Http.golden
  api/pkg/service/resource/testdata/TestByID_Http.golden
  api/pkg/service/resource/testdata/TestByID_V1_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_V1_Http.golden
  api/pkg/service/resource/testdata/TestDeprecationByVersionID_Http.golden
  api/pkg/service/resource/testdata/TestLatestVersionDeprecationByID_Http.golden
  api/pkg/service/resource/testdata/TestList_Http_NoLimit.golden
  api/pkg/service/resource/testdata/TestList_Http_WithLimit.golden
  api/pkg/service/resource/testdata/TestList_V1_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithAllParams_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithCategoriesAndKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithCategoriesAndName_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithCategoriesAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithCategories_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithExactName_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKindsAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithPlatforms_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithTags_Http.golden
  api/pkg/service/resource/testdata/TestQuery_Http.golden
  api/pkg/service/resource/testdata/TestQuery_V1_Http.golden
  api/pkg/service/resource/testdata/TestVersionsByID_Http.golden
  api/pkg/service/resource/testdata/TestVersionsByID_V1_Http.golden
Labels: approved, lgtm, size/XXL

#364 Fixes error handling condition for login
  ui/src/containers/ParseUrl/index.tsx
Labels: approved, size/XS, lgtm

#365 Adds `Vinamra` as Hub Owner 🎉
  OWNERS
Labels: approved, size/XS, lgtm

#362 Update Deployment and Development docs based on new auth changes
  docs/DEPLOYMENT.md
  docs/DEVELOPMENT.md
Labels: approved, lgtm, size/L

#366 Add annotations in ingress for API and Auth and rename oauth to auth
  config/02-api/23-api-service.yaml
  config/04-kubernetes/40-api-ingress.yaml
  config/04-kubernetes/40-auth-ingress.yaml
  config/04-openshift/40-auth-route.yaml
  docs/DEPLOYMENT.md
  release.sh
Labels: approved, lgtm, size/S

#368 Update ingress for swagger
  config/06-swagger/01-kubernetes/01-swagger-ingress.yaml
Labels: approved, size/XS, lgtm

#369 Fix Generation of Raw Readme and YAMLs in v1 APIs
  api/v1/service/resource/resource.go
  api/v1/service/resource/resource_test.go
Labels: approved, lgtm, size/M

#370 Adds Hub Swagger UI url in readme
  README.md
Labels: approved, size/XS, lgtm

#382 Fixes username check when the pod gets restarted
  api/pkg/db/initializer/initializer.go
Labels: approved, size/XS, lgtm
