Repository tektoncd/hub, pull requests merged in 2022-06, with the labels that each got.

#522 dependabot: move to a weekly basis
  .github/dependabot.yml
Labels: approved, size/XS, lgtm

#525 Add label dependabot PRs ok-to-test…
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#543 Adds `POSTGRES_HOST` as a secret for db
  config/00-init/01-db-secret.yaml
  config/01-db/10-db-migration.yaml
  config/02-api/22-api-deployment.yaml
Labels: approved, lgtm, size/S

#541 Skip to read JWTconfig env if AUTH_BASE_URL is empty
  api/.env.dev
  api/pkg/app/app.go
Labels: approved, lgtm, size/S

#542 Disable login and rating on UI
  ui/src/containers/BasicDetails/index.tsx
  ui/src/containers/Header/index.tsx
Labels: approved, lgtm, size/S

#548 Update UI dockerfile to include .npmrc file
  images/ui.Dockerfile
  ui/.npmrc
  ui/package-lock.json
Labels: approved, lgtm, size/M

#539 [TEP-0110] Add an Endpoint for Fetching a Raw Tekton Resource YAML File
  api/v1/design/resource.go
  api/v1/gen/http/cli/hub/cli.go
  api/v1/gen/http/openapi.json
  api/v1/gen/http/openapi.yaml
  api/v1/gen/http/openapi3.json
  api/v1/gen/http/openapi3.yaml
  api/v1/gen/http/resource/client/cli.go
  api/v1/gen/http/resource/client/client.go
  api/v1/gen/http/resource/client/encode_decode.go
  api/v1/gen/http/resource/client/paths.go
  api/v1/gen/http/resource/client/types.go
  api/v1/gen/http/resource/server/encode_decode.go
  api/v1/gen/http/resource/server/paths.go
  api/v1/gen/http/resource/server/server.go
  api/v1/gen/http/resource/server/types.go
  api/v1/gen/resource/client.go
  api/v1/gen/resource/endpoints.go
  api/v1/gen/resource/service.go
  api/v1/service/resource/resource.go
  api/v1/service/resource/resource_http_test.go
  api/v1/service/resource/resource_test.go
Labels: kind/feature, approved, lgtm, size/XXL
