Repository tektoncd/hub, pull requests merged in 2022-03, with the labels that each got.

#384 Replace git.maze.io/go/duration to github.com/hako/durafmt
  api/pkg/app/app.go
  api/pkg/app/app_test.go
  docs/DEPLOYMENT.md
  go.mod
  go.sum
  vendor/git.maze.io/go/duration/.drone.yml
  vendor/git.maze.io/go/duration/LICENSE
  vendor/git.maze.io/go/duration/README.md
  vendor/git.maze.io/go/duration/duration.go
  vendor/github.com/hako/durafmt/.gitignore
  vendor/github.com/hako/durafmt/.travis.yml
  vendor/github.com/hako/durafmt/CODE_OF_CONDUCT.md
  vendor/github.com/hako/durafmt/CONTRIBUTING.md
  vendor/github.com/hako/durafmt/LICENSE
  vendor/github.com/hako/durafmt/README.md
  vendor/github.com/hako/durafmt/durafmt.go
  vendor/github.com/hako/durafmt/go.mod
  vendor/github.com/hako/durafmt/unit.go
  vendor/github.com/markbates/goth/providers/gitlab/gitlab.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#385 Trims Api and UI config urls
  api/pkg/auth/base.go
  ui/src/common/trimUrl.test.ts
  ui/src/common/trimUrl.ts
  ui/src/config/constants.tsx
Labels: approved, lgtm, size/M

#386 Removes hub preview APIs for resources
  api/cmd/api/http.go
  api/cmd/api/main.go
  api/design/api.go
  api/design/resource.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/rating/client/cli.go
  api/gen/http/resource/client/cli.go
  api/gen/http/resource/client/client.go
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/client/paths.go
  api/gen/http/resource/client/types.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/paths.go
  api/gen/http/resource/server/server.go
  api/gen/http/resource/server/types.go
  api/gen/resource/client.go
  api/gen/resource/endpoints.go
  api/gen/resource/service.go
  api/gen/resource/views/view.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestByCatalogKindNameVersion_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindNameVersion_V1_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_CompatibleVersion_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_Http.golden
  api/pkg/service/resource/testdata/TestByCatalogKindName_V1_Http.golden
  api/pkg/service/resource/testdata/TestByEnterpriseCatalogKindName_Http.golden
  api/pkg/service/resource/testdata/TestByID_Http.golden
  api/pkg/service/resource/testdata/TestByID_V1_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_Http.golden
  api/pkg/service/resource/testdata/TestByVersionID_V1_Http.golden
  api/pkg/service/resource/testdata/TestDeprecationByVersionID_Http.golden
  api/pkg/service/resource/testdata/TestLatestVersionDeprecationByID_Http.golden
  api/pkg/service/resource/testdata/TestList_Http_NoLimit.golden
  api/pkg/service/resource/testdata/TestList_Http_WithLimit.golden
  api/pkg/service/resource/testdata/TestList_V1_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithAllParams_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithCategoriesAndKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithCategoriesAndName_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithCategoriesAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithCategories_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithExactName_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKindsAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndKinds_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithNameAndTags_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithPlatforms_Http.golden
  api/pkg/service/resource/testdata/TestQueryWithTags_Http.golden
  api/pkg/service/resource/testdata/TestQuery_Http.golden
  api/pkg/service/resource/testdata/TestQuery_V1_Http.golden
  api/pkg/service/resource/testdata/TestVersionsByID_Http.golden
  api/pkg/service/resource/testdata/TestVersionsByID_V1_Http.golden
Labels: approved, lgtm, size/XXL

#390 Bump golang to 1.16 in Dockerfile
  images/api.Dockerfile
  images/db.Dockerfile
Labels: approved, size/XS, lgtm

#379 Updates deployment configs to include the prefix `tekton-hub-`
  config/00-init/01-db-secret.yaml
  config/00-init/02-db-pvc.yaml
  config/00-init/03-db-deployment.yaml
  config/00-init/04-db-service.yaml
  config/01-db/10-db-migration.yaml
  config/02-api/20-api-pvc.yaml
  config/02-api/20-api-secret.yaml
  config/02-api/21-api-configmap.yaml
  config/02-api/22-api-deployment.yaml
  config/02-api/23-api-service.yaml
  config/03-ui/30-ui-configmap.yaml
  config/03-ui/31-ui-deployment.yaml
  config/03-ui/32-ui-service.yaml
  config/04-kubernetes/40-api-ingress.yaml
  config/04-kubernetes/40-auth-ingress.yaml
  config/04-kubernetes/42-hub-preview-redirect-ingress.yaml
  config/04-kubernetes/42-ui-ingress.yaml
  config/04-openshift/40-api-route.yaml
  config/04-openshift/40-auth-route.yaml
  config/04-openshift/41-ui-route.yaml
  config/05-catalog-refresh-cj/51-catalog-refresh-cronjob.yaml
Labels: approved, lgtm, size/L

#389 Adds a doc for upgrading Hub v1.6.0 to v1.7.0
  docs/DEPLOYMENT.md
  docs/DEVELOPMENT.md
  docs/UPGRADE_V1.6.0_TO_V1.7.0.md
Labels: approved, lgtm, size/L

#391 Fixes the path for building the images in release.sh
  release.sh
Labels: approved, size/XS, lgtm

#392 Minor fix in release.sh
  release.sh
Labels: approved, lgtm, size/M

#393 Fixes platform name while replacing the image in release script
  release.sh
Labels: approved, size/XS, lgtm

#394 Fixes file attachments in release script
  release.sh
Labels: approved, size/XS, lgtm

#396 Change catalog default clone path and update docs
  api/pkg/git/git.go
  config/02-api/22-api-deployment.yaml
  config/05-catalog-refresh-cj/51-catalog-refresh-cronjob.yaml
  config/06-swagger/01-kubernetes/01-swagger-ingress.yaml
  docs/DEPLOYMENT.md
Labels: approved, lgtm, size/M

#397 Revert `/resource/{id}/versions` api
  api/cmd/api/main.go
  api/design/resource.go
  api/gen/http/cli/hub/cli.go
  api/gen/http/openapi.json
  api/gen/http/openapi.yaml
  api/gen/http/openapi3.json
  api/gen/http/openapi3.yaml
  api/gen/http/resource/client/cli.go
  api/gen/http/resource/client/client.go
  api/gen/http/resource/client/encode_decode.go
  api/gen/http/resource/client/paths.go
  api/gen/http/resource/client/types.go
  api/gen/http/resource/server/encode_decode.go
  api/gen/http/resource/server/paths.go
  api/gen/http/resource/server/server.go
  api/gen/http/resource/server/types.go
  api/gen/resource/client.go
  api/gen/resource/endpoints.go
  api/gen/resource/service.go
  api/gen/resource/views/view.go
  api/pkg/service/resource/resource.go
  api/pkg/service/resource/resource_http_test.go
  api/pkg/service/resource/resource_test.go
  api/pkg/service/resource/testdata/TestVersionsByID_Http.golden
Labels: approved, lgtm, size/XXL

#402 Add GOMAXPROCS to support k8s CPU quota
  api/cmd/api/main.go
  go.mod
  go.sum
  vendor/github.com/markbates/goth/providers/gitlab/gitlab.go
  vendor/go.uber.org/automaxprocs/.codecov.yml
  vendor/go.uber.org/automaxprocs/.gitignore
  vendor/go.uber.org/automaxprocs/.travis.yml
  vendor/go.uber.org/automaxprocs/CHANGELOG.md
  vendor/go.uber.org/automaxprocs/CODE_OF_CONDUCT.md
  vendor/go.uber.org/automaxprocs/CONTRIBUTING.md
  vendor/go.uber.org/automaxprocs/LICENSE
  vendor/go.uber.org/automaxprocs/Makefile
  vendor/go.uber.org/automaxprocs/README.md
  vendor/go.uber.org/automaxprocs/automaxprocs.go
  vendor/go.uber.org/automaxprocs/glide.yaml
  vendor/go.uber.org/automaxprocs/go.mod
  vendor/go.uber.org/automaxprocs/go.sum
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroup.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/cgroups.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/doc.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/errors.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/mountpoint.go
  vendor/go.uber.org/automaxprocs/internal/cgroups/subsys.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_linux.go
  vendor/go.uber.org/automaxprocs/internal/runtime/cpu_quota_unsupported.go
  vendor/go.uber.org/automaxprocs/internal/runtime/runtime.go
  vendor/go.uber.org/automaxprocs/maxprocs/maxprocs.go
  vendor/go.uber.org/automaxprocs/maxprocs/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#407 Add dependabot configuration
  .github/dependabot.yml
Labels: approved, lgtm, size/S, kind/misc

#408 Fix dependabot configuration… 🤦
  .github/dependabot.yml
Labels: approved, size/XS, lgtm
