Repository tektoncd/hub, pull requests merged in 2023-02, with the labels that each got.

#786 Uses alpine as the base image for nginx in UI dockerfile
  images/ui.Dockerfile
Labels: approved, size/XS, lgtm

#780 Fixes to support v1beta1 and v1 API version for install command
  api/pkg/cli/installer/gvr.go
  api/pkg/cli/installer/kube_action.go
Labels: approved, lgtm, size/M

#798 Updates react-markdown to 8.0.5
  ui/jest.config.js
  ui/package-lock.json
  ui/package.json
  ui/src/__test__/__mocks__/react-markdown.js
  ui/src/components/Description/Description.css
  ui/src/components/Description/index.tsx
  ui/src/components/LeftPane/__snapshots__/LeftPane.test.tsx.snap
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/BasicDetails/__snapshots__/BasicDetails.test.tsx.snap
  ui/src/containers/CatalogFilter/__snapshots__/CatalogFilter.test.tsx.snap
  ui/src/containers/CategoryFilter/__snapshots__/CategoryFilter.test.tsx.snap
  ui/src/containers/Header/__snapshots__/Header.test.tsx.snap
  ui/src/containers/KindFilter/__snapshots__/KindFilter.test.tsx.snap
  ui/src/containers/PlatformFilter/__snapshots__/PlatformFilter.test.tsx.snap
  ui/src/containers/Resources/__snapshots__/Resources.test.tsx.snap
Labels: approved, lgtm, size/XXL

#801 Fixes test after axios is bumped to the 1.33 version
  ui/jest.config.js
  ui/package-lock.json
  ui/package.json
  ui/src/__mocks__/axios.js
Labels: approved, lgtm, size/XXL

#779 Fixes UI page redirection after authentication
  ui/src/containers/Header/index.tsx
  ui/src/store/auth.ts
Labels: approved, lgtm, size/S

#820 Add dependant bot for swagger and update schedule to daily
  .github/dependabot.yml
  .github/pull_request_template.md
  api/.gitignore
Labels: approved, lgtm, size/M

#828 Bump UI npm packages to latest
  ui/package-lock.json
  ui/package.json
Labels: approved, lgtm, size/XXL

#833 Bump react-dom to 17.0.0 in UI
  ui/package-lock.json
  ui/package.json
  ui/src/setupTests.ts
Labels: approved, lgtm, size/XL
