Repository tektoncd/hub, pull requests merged in 2023-01, with the labels that each got.

#748 Updates Footer snapshots
  ui/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
Labels: approved, size/XS, lgtm

#749 Fixes user's id parsing in the user info api
  api/pkg/user/service/user.go
  api/pkg/user/service/user_test.go
Labels: approved, lgtm, size/M

#760 Fixes resource category mapping
  api/pkg/db/initializer/initializer.go
Labels: approved, lgtm, size/S

#752 Refactor get_resource and get_resource_version for multiple hub support
  api/pkg/cli/hub/get_resource.go
  api/pkg/cli/hub/get_resource_version.go
Labels: approved, lgtm, size/L

#771 Fix description in `tkn hub` command
  api/pkg/cli/cmd/root.go
Labels: approved, size/XS, lgtm

#757 Implement "install" command for artifact type
  api/pkg/cli/cmd/check_upgrade/check_upgrade_test.go
  api/pkg/cli/cmd/downgrade/downgrade_test.go
  api/pkg/cli/cmd/get/get_test.go
  api/pkg/cli/cmd/get/task_test.go
  api/pkg/cli/cmd/info/info_test.go
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/cmd/install/install_test.go
  api/pkg/cli/cmd/reinstall/reinstall_test.go
  api/pkg/cli/cmd/search/search_test.go
  api/pkg/cli/cmd/upgrade/upgrade_test.go
  api/pkg/cli/hub/get_catalog.go
  api/pkg/cli/hub/get_resource.go
  api/pkg/cli/hub/get_resource_version.go
  api/pkg/cli/hub/hub.go
  api/pkg/cli/hub/search.go
  api/pkg/cli/test/config.go
Labels: approved, lgtm, size/XL

#775 [TEP-0079] Add Support Tier in tkn hub install command
  api/pkg/cli/cmd/install/install.go
  api/pkg/cli/hub/get_catalog.go
  api/pkg/cli/hub/get_resource.go
  api/pkg/cli/hub/get_resource_version.go
  api/pkg/cli/hub/hub.go
  api/pkg/cli/hub/hub_test.go
  api/pkg/cli/hub/search.go
  api/pkg/cli/installer/action.go
  api/pkg/cli/installer/action_test.go
Labels: approved, lgtm, size/L

#774 Fixes `check-upgrade` example's description
  api/pkg/cli/cmd/check_upgrade/check_uprade.go
Labels: approved, size/XS, lgtm
