Repository tektoncd/hub, pull requests merged in 2023-03, with the labels that each got.

#861 Fixes Hub API to support `v1` api's of Tekton Resource
  api/pkg/parser/catalog.go
  api/pkg/parser/parser.go
Labels: approved, size/XS, lgtm

#855 Fix swagger UI and remove unused prettier plugin
  swagger/.eslintrc.json
  swagger/Dockerfile
Labels: approved, lgtm, size/S

#802 Fixes warning in Hub UI tests by removing deprecated `useobserver `
  ui/src/components/Description/index.tsx
  ui/src/components/Filter/index.tsx
  ui/src/components/HomePage/HomePage.test.tsx
  ui/src/components/HomePage/__snapshots__/HomePage.test.tsx.snap
  ui/src/components/HomePage/index.tsx
  ui/src/components/LeftPane/__snapshots__/LeftPane.test.tsx.snap
  ui/src/components/LeftPane/index.tsx
  ui/src/components/ResourceDetailsPage/ResourceDetailsPage.test.tsx
  ui/src/components/ResourceDetailsPage/__snapshots__/ResourceDetailsPage.test.tsx.snap
  ui/src/components/ResourceDetailsPage/index.tsx
  ui/src/containers/App/App.test.tsx
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/App/index.tsx
  ui/src/containers/BasicDetails/__snapshots__/BasicDetails.test.tsx.snap
  ui/src/containers/BasicDetails/index.tsx
  ui/src/containers/CatalogFilter/__snapshots__/CatalogFilter.test.tsx.snap
  ui/src/containers/CatalogFilter/index.tsx
  ui/src/containers/CategoryFilter/__snapshots__/CategoryFilter.test.tsx.snap
  ui/src/containers/CategoryFilter/index.tsx
  ui/src/containers/KindFilter/__snapshots__/KindFilter.test.tsx.snap
  ui/src/containers/KindFilter/index.tsx
  ui/src/containers/PlatformFilter/__snapshots__/PlatformFilter.test.tsx.snap
  ui/src/containers/PlatformFilter/index.tsx
  ui/src/containers/SortDropDown/index.tsx
Labels: approved, lgtm, size/XXL

#910 Adds comma in the server script for UI
  ui/image/start.sh
Labels: approved, size/XS, lgtm
