Repository tektoncd/hub, pull requests merged in 2023-08, with the labels that each got.

#992 Bump webpack from 5.74.0 to 5.76.1 in /ui
  ui/package-lock.json
Labels: approved, lgtm, size/S

#1030 Bump go to 1.20
  .github/workflows/goa-gen-dependabot.yml
  go.mod
Labels: approved, size/XS, lgtm

#1036 Bump core-js-compat and semver
  ui/package-lock.json
  ui/package.json
Labels: approved, lgtm, size/L

#1049 Fixes UI build
  ui/package-lock.json
  ui/package.json
Labels: approved, lgtm, size/XXL

#1050 Updates prettier to fix lint errors
  ui/package-lock.json
  ui/package.json
  ui/src/containers/App/App.test.tsx
  ui/src/setupTests.ts
Labels: approved, lgtm, size/XL
