Repository tektoncd/hub, pull requests merged in 2024-01, with the labels that each got.

#1104 Adds a configMap named `hub-info` to have the Hub version
  config/07-hub-info/hub-info.yaml
  config/07-hub-info/role-binding.yaml
  release.sh
Labels: approved, lgtm, size/M

#1312 Updates UI Snapshots
  ui/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
Labels: approved, size/XS, lgtm

#1314 Bumps axios to 1.6.5 in UI
  ui/package-lock.json
  ui/package.json
Labels: approved, lgtm, size/M

#1324 Bump mobx-state-tree from 5.1.8 to 5.4.0 in /ui
  ui/package-lock.json
  ui/package.json
  ui/src/components/LeftPane/__snapshots__/LeftPane.test.tsx.snap
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
  ui/src/containers/CatalogFilter/__snapshots__/CatalogFilter.test.tsx.snap
  ui/src/containers/CategoryFilter/__snapshots__/CategoryFilter.test.tsx.snap
  ui/src/containers/KindFilter/__snapshots__/KindFilter.test.tsx.snap
  ui/src/containers/PlatformFilter/__snapshots__/PlatformFilter.test.tsx.snap
Labels: approved, lgtm, size/M

#1349 Bump prettier from 3.0.3 to 3.1.1 in /ui
  ui/package-lock.json
  ui/package.json
  ui/src/containers/Resources/index.tsx
  ui/src/containers/SortDropDown/index.tsx
Labels: approved, lgtm, size/S

#1393 Bump react-markdown from 8.0.7 to 9.0.1 in /ui
  ui/package-lock.json
  ui/package.json
  ui/src/__test__/__mocks__/rehype-external-links.js
  ui/src/components/Description/index.tsx
Labels: approved, lgtm, size/XXL

#1413 Fix broken link in contributing guide
  CONTRIBUTING.md
Labels: approved, kind/documentation, size/XS, lgtm
