Repository tektoncd/hub, pull requests merged in 2024-05, with the labels that each got.

#1706 Bump golang to 1.22
  .github/workflows/goa-gen-dependabot.yml
  go.mod
  go.sum
  vendor/github.com/go-faster/city/_testdata/ch128.csv
  vendor/github.com/go-faster/city/_testdata/data.json
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures/assets.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures/comments.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures/posts.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures/posts_tags.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures/tags.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures/users.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures/votes.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_dirs/fixtures1/comments.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_dirs/fixtures1/posts.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_dirs/fixtures1/posts_tags.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_dirs/fixtures2/tags.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_dirs/fixtures2/users.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_multi_tables/assets.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_multi_tables/posts_comments.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_multi_tables/posts_tags.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_multi_tables/tags.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/fixtures_multi_tables/users.yml
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/schema/clickhouse.sql
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/schema/mysql.sql
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/schema/postgresql.sql
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/schema/sqlite.sql
  vendor/github.com/go-testfixtures/testfixtures/v3/testdata/schema/sqlserver.sql
Labels: approved, lgtm, size/XXL

#1708 npm audit fix for swagger
  swagger/package-lock.json
Labels: approved, lgtm, size/L

#1728 fix: Typo in Docker Buildx command in DEPLOYMENT
  docs/DEPLOYMENT.md
Labels: approved, size/XS, lgtm, ok-to-test
