Repository tektoncd/hub, pull requests merged in 2024-07, with the labels that each got.

#1807 Bump webpack-dev-server package
  ui/package-lock.json
  ui/package.json
Labels: approved, lgtm, size/XXL

#1812 Ignore major minor k8s in dependent bot
  .github/dependabot.yml
Labels: approved, size/XS, lgtm

#1818 Bump jsdom to latest version
  swagger/package-lock.json
  swagger/package.json
Labels: approved, lgtm, size/XXL

#1847 Bumps micromatch to 4.0.7
  ui/package-lock.json
  ui/package.json
Labels: approved, lgtm, size/S
