Repository tektoncd/hub, pull requests merged in 2025-01, with the labels that each got.

#2237 Update UI test snapshot
  ui/src/components/Footer/__snapshots__/Footer.test.tsx.snap
  ui/src/containers/App/__snapshots__/App.test.tsx.snap
Labels: approved, size/XS, lgtm

#2246 Update go dependencies because of CVE-2024-45338
  go.mod
  go.sum
Labels: kind/bug, approved, size/XS, lgtm, ok-to-test

#2249 update vendor directory for updated go dependencies
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, ok-to-test, size/XL

#2252 Update go.sum file
  go.sum
Labels: approved, lgtm, size/L
